import { firebaseService } from './services/firebase.js?v=3';
import { geminiService } from './services/gemini.js?v=2';
import { LiveSpeakingService } from './services/live-speaking.js?v=2';
import { initPwaInstall, refreshPwaInstall } from './services/pwa-install.js?v=1';
import { store } from './core/store.js';
import { scoreDiagnostic, createPlan, adaptNextWeek, masteryBySkill, calculateStreak } from './core/plan-engine.js?v=3';

const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const html = (value='') => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const today = () => new Date().toISOString().slice(0,10);
const skillLabels = { vocabulary:'Từ vựng',grammar:'Ngữ pháp',reading:'Reading',writing:'Writing',listening:'Listening',speaking:'Speaking',mixed:'Tổng hợp' };
const reasonLabels = { CURRICULUM_CORE:'Nội dung cốt lõi',SELF_REPORTED_WEAK:'Kỹ năng bạn muốn cải thiện',DIAGNOSTIC_GAP:'Khoảng trống từ bài đầu vào',LOW_MASTERY:'Cần củng cố theo kết quả',MISSED_SESSIONS:'Bài chưa hoàn thành',WEEKLY_REBALANCE:'Điều chỉnh cuối tuần' };
let curriculum, diagnostic, currentUser, currentStep=1, liveService=null, activityStartedAt=0;

function toast(message) {
  const node=document.createElement('div');node.className='toast';node.textContent=message;$('#toast-region').append(node);setTimeout(()=>node.remove(),4200);
}
function icon(name) {
  const paths={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',moon:'<path d="M20.5 14.5A8 8 0 0 1 9.5 3.5 8.5 8.5 0 1 0 20.5 14.5Z"/>',arrow:'<path d="m9 18 6-6-6-6"/>',back:'<path d="m15 18-6-6 6-6"/>',play:'<path d="m8 5 11 7-11 7V5Z"/>',mic:'<path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2M12 19v3"/>',check:'<path d="m5 12 4 4L19 6"/>',volume:'<path d="M11 5 6 9H2v6h4l5 4V5ZM15 9a4 4 0 0 1 0 6M18 6a8 8 0 0 1 0 12"/>',spark:'<path d="m12 3 1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5L12 3ZM5 15l.8 2.2L8 18l-2.2.8L5 21l-.8-2.2L2 18l2.2-.8L5 15Z"/>',logout:'<path d="M10 17l5-5-5-5M15 12H3M14 3h5a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-5"/>'};return `<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]||''}</svg>`;
}

async function init() {
  initPwaInstall({notify:toast});
  [curriculum,diagnostic]=await Promise.all([fetch('./data/curriculum.json').then(r=>r.json()),fetch('./data/diagnostic.json').then(r=>r.json())]);
  bindGlobal();renderDiagnostic();
  firebaseService.onAuth(handleAuth);
  try { await firebaseService.init(); firebaseService.restoreDemo(); } catch(error) { showAuthError(error.message); }
  if(firebaseService.demo){$('#demo-login-btn').hidden=false;$('#auth-hint').textContent='Firebase chưa cấu hình. Dùng demo để kiểm tra toàn bộ luồng trên thiết bị này.';}
  updateNetwork();registerServiceWorker();
}

function bindGlobal() {
  $('#google-login-btn').onclick=async()=>{setLoginBusy(true);try{await firebaseService.login()}catch(error){showAuthError(error.message)}finally{setLoginBusy(false)} };
  $('#demo-login-btn').onclick=()=>firebaseService.loginDemo();
  $('#onboarding-logout').onclick=()=>firebaseService.logout();
  $('#step-next').onclick=nextStep;$('#step-back').onclick=previousStep;$('#onboarding-form').onsubmit=submitOnboarding;
  $('[name="daysPerWeek"]').addEventListener('input',e=>$('#days-output').value=`${e.target.value} ngày`);
  $$('[name="track"]').forEach(input=>input.addEventListener('change',updateTrackFields));
  window.addEventListener('hashchange',route);window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);
  $('#mobile-theme').addEventListener('click',toggleTheme);
  window.addEventListener('beforeunload',()=>liveService?.stop());document.addEventListener('visibilitychange',()=>{if(document.hidden&&liveService)liveService.stopMicrophone()});
}

function setLoginBusy(value){$('#google-login-btn').disabled=value;$('#google-login-btn').lastChild.textContent=value?' Đang đăng nhập...':' Tiếp tục với Google';}
function showAuthError(message){$('#auth-error').hidden=false;$('#auth-error').textContent=message;}
function updateNetwork(){const offline=!navigator.onLine;$('#network-banner').hidden=!offline;document.body.classList.toggle('is-offline',offline);}

async function handleAuth(user) {
  currentUser=user;
  $('#auth-screen').hidden=!!user;
  if(!user){$('#onboarding-screen').hidden=true;$('#app-shell').hidden=true;return;}
  store.load(user.uid,{displayName:user.displayName||'Học viên',email:user.email||'',photoURL:user.photoURL||''});
  if(!firebaseService.demo){try{const remote=await firebaseService.loadUserData(user.uid);store.mergeRemote(remote);if(store.activePlan)await firebaseService.savePlan(user.uid,store.activePlan)}catch(error){toast(`Đồng bộ chưa hoàn tất: ${error.message}`)}}
  await firebaseService.upsertProfile(user,store.state.onboardingComplete,store.state.currentPlanId).catch(()=>{});
  renderProfile();
  if(store.state.onboardingComplete&&store.activePlan)showApp();else showOnboarding();
}

function showOnboarding(){currentStep=1;$('#onboarding-screen').hidden=false;$('#app-shell').hidden=true;renderStep();}
function showApp(){ $('#onboarding-screen').hidden=true;$('#app-shell').hidden=false;if(!location.hash||location.hash==='#/')location.hash='#/today';route(); }
function renderProfile(){const p=store.state.profile||{};$('#sidebar-profile').innerHTML=`<div class="profile-row">${p.photoURL?`<img src="${html(p.photoURL)}" alt="">`:`<span class="avatar-fallback">${html((p.displayName||'H')[0])}</span>`}<div><strong>${html(p.displayName||'Học viên')}</strong><small>${html(p.email||'Demo local')}</small></div></div>`;}

function renderDiagnostic() {
  $('#diagnostic-questions').innerHTML=diagnostic.map((q,index)=>`<article class="question-card"><fieldset><legend>${index+1}. ${html(q.prompt)}</legend><div class="answer-options">${q.options.map((option,i)=>`<label><input type="radio" name="diagnostic-${q.id}" value="${i}" required><span>${html(option)}</span></label>`).join('')}</div></fieldset></article>`).join('');
}
function updateTrackFields(){const track=$('[name="track"]:checked')?.value;$('#ielts-fields').hidden=track!=='ielts';$('#communication-context-field').hidden=track!=='communication';}
function renderStep(){$$('.wizard-step').forEach(step=>step.hidden=Number(step.dataset.step)!==currentStep);$('#step-progress-label').textContent=`Bước ${currentStep} / 4`;$('#step-progress-fill').style.width=`${currentStep*25}%`;$('#step-back').hidden=currentStep===1;$('#step-next').hidden=currentStep===4;$('#create-plan').hidden=currentStep!==4;$('#form-error-summary').hidden=true;updateTrackFields();$('.wizard-step:not([hidden]) h1')?.focus?.();}
function validateStep(){const step=$(`.wizard-step[data-step="${currentStep}"]`);const inputs=$$('input,select,textarea',step);for(const input of inputs){if(!input.checkValidity()){showFormError(input.validationMessage||'Hãy hoàn thành thông tin bắt buộc.',input);return false;}}if(currentStep===3){for(const q of diagnostic){if(!$(`[name="diagnostic-${q.id}"]:checked`)){showFormError('Hãy trả lời đủ 8 câu diagnostic.',$(`[name="diagnostic-${q.id}"]`));return false;}}}return true;}
function showFormError(message,input){const box=$('#form-error-summary');box.textContent=message;box.hidden=false;box.focus();input?.focus();}
function nextStep(){if(!validateStep())return;currentStep=Math.min(4,currentStep+1);renderStep();window.scrollTo({top:0});}
function previousStep(){currentStep=Math.max(1,currentStep-1);renderStep();window.scrollTo({top:0});}

async function submitOnboarding(event) {
  event.preventDefault();if(!validateStep())return;const button=$('#create-plan');button.disabled=true;button.textContent='Đang tạo lộ trình...';
  try { const formData=new FormData(event.currentTarget),result=scoreDiagnostic(diagnostic,formData),plan=createPlan({formData,diagnostic:result,curriculum});store.setPlan(plan);await Promise.all([firebaseService.savePlan(currentUser.uid,plan),firebaseService.upsertProfile(currentUser,true,plan.id)]);toast(`Đã tạo lộ trình ${plan.track==='ielts'?'IELTS':'Giao tiếp'} phù hợp mức ${result.inferredLevel}.`);showApp(); }
  catch(error){showFormError(error.message)}finally{button.disabled=false;button.textContent='Tạo lộ trình của tôi';}
}

function route() {
  if(!currentUser||$('#app-shell').hidden)return;
  if(liveService){liveService.stop();liveService=null;}
  const parts=(location.hash.replace(/^#\//,'')||'today').split('/'),name=parts[0];
  $$('[data-route]').forEach(link=>link.classList.toggle('active',link.dataset.route===name));
  const content=$('#main-content');content.innerHTML='';
  if(name==='activity')renderActivity(parts[1]);else if(name==='roadmap')renderRoadmap();else if(name==='review')renderReview();else if(name==='progress')renderProgress();else if(name==='settings')renderSettings();else renderToday();
  updateReviewBadge();content.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});
}
function planSessions(){
  const plan=store.activePlan;if(!plan)return[];
  const sourceById=new Map((curriculum?.tracks?.[plan.track]||[]).map(session=>[session.id,session]));
  return [...(plan.sessions||[])].map(assignment=>({...sourceById.get(assignment.id),...assignment})).sort((a,b)=>a.order-b.order);
}
function nextSession(){const done=store.completedIds;return planSessions().find(s=>!done.has(s.id))||planSessions().at(-1)}
function progressPercent(){const sessions=planSessions();return sessions.length?Math.round(100*sessions.filter(s=>store.completedIds.has(s.id)).length/sessions.length):0}
function dueReviews(){return Object.values(store.state.reviewItems).filter(item=>item.nextReviewAt<=today())}
function updateReviewBadge(){const count=dueReviews().length,b=$('#review-badge');b.textContent=count;b.hidden=!count;}
function pageHeader(title,description,actions=''){return `<header class="page-header"><div><div class="eyebrow">YOUR ENGLISH JOURNEY</div><h1>${title}</h1>${description?`<p class="lead">${description}</p>`:''}</div><div class="header-actions">${actions}</div></header>`}

function renderToday() {
  const plan=store.activePlan,session=nextSession(),progress=progressPercent(),streak=calculateStreak(store.state.studyDays),reviews=dueReviews().length;
  $('#main-content').innerHTML=`<div class="page"><section class="hero-panel"><div><div class="eyebrow" style="color:#99f6e4">${plan.track==='ielts'?'IELTS PATH':'COMMUNICATION PATH'} · TUẦN ${plan.weekIndex}</div><h1>${greeting()}, ${html((store.state.profile?.displayName||'bạn').split(' ')[0])}.<br>Tiến thêm một bước hôm nay.</h1><p>${session?`Phiên tiếp theo tập trung vào ${skillLabels[session.skill]||session.skill}.`:'Bạn đã hoàn thành lộ trình mẫu.'}</p>${session?`<a class="btn" href="#/activity/${session.id}">${icon('play')} Bắt đầu · ${session.minutes} phút</a>`:''}</div><div class="hero-score" style="--progress:${progress}%"><span>${progress}%<small>HOÀN THÀNH</small></span></div></section>
  <div class="stats-grid"><div class="stat-card"><span>Chuỗi học</span><strong>${streak} ngày</strong></div><div class="stat-card"><span>Đã hoàn thành</span><strong>${store.completedIds.size}/10</strong></div><div class="stat-card"><span>Cần ôn hôm nay</span><strong>${reviews} mục</strong></div><div class="stat-card"><span>Nhịp học</span><strong>${plan.schedule.minutesPerDay} phút</strong></div></div>
  <div class="section-heading"><h2>Kế hoạch hôm nay</h2><a href="#/roadmap">Xem lộ trình</a></div><div class="today-grid">${sessionCard(session)}<aside class="card review-card"><span class="skill-tag">Ôn tập thông minh</span><p class="review-count">${reviews}</p><h3>${reviews?'mục đang chờ bạn':'Bạn đã ôn xong'}</h3><p class="muted">Các lỗi sai quay lại theo nhịp 1–3–7 ngày.</p><a href="#/review" class="btn btn-secondary">Mở ôn tập</a></aside></div></div>`;
}
function greeting(){const h=new Date().getHours();return h<11?'Chào buổi sáng':h<18?'Chào buổi chiều':'Chào buổi tối'}
function sessionCard(session){if(!session)return `<div class="card empty-state"><h2>Hoàn thành xuất sắc</h2><p>Bạn đã kết thúc curriculum MVP.</p></div>`;return `<article class="card lesson-card"><div class="lesson-card-top"><span class="skill-tag">${skillLabels[session.skill]||session.skill}</span><span class="status-pill">Phiên ${session.order}/10</span></div><h3>${html(session.title)}</h3><p class="muted">${html(session.reason)}</p><div class="meta-row"><span>${session.minutes} phút</span><span>${session.activities.length} hoạt động</span><span>${html(session.level)}</span></div><a class="btn btn-primary" href="#/activity/${session.id}">${icon('play')} Bắt đầu phiên học</a></article>`}

function renderRoadmap() {
  const plan=store.activePlan,done=store.completedIds,weekOneDone=plan.sessions.filter(s=>s.week===1).every(s=>done.has(s.id));
  $('#main-content').innerHTML=`<div class="page">${pageHeader('Lộ trình 2 tuần',`${plan.track==='ielts'?'IELTS':'Giao tiếp'} · ${plan.schedule.daysPerWeek} ngày/tuần · ${plan.schedule.minutesPerDay} phút/ngày`,weekOneDone&&!plan.adaptations.length?'<button id="adapt-plan" class="btn btn-primary">Điều chỉnh tuần 2</button>':'')}<div class="inline-alert info">Lộ trình dùng curriculum đã kiểm duyệt. Các nhãn bên dưới giải thích vì sao một phiên được chọn cho bạn.</div><div class="timeline">${[1,2].map(week=>`<section class="timeline-week"><div class="timeline-week-title"><strong>Tuần ${week}</strong></div>${planSessions().filter(s=>s.week===week).map(s=>timelineItem(s,done)).join('')}</section>`).join('')}</div>${plan.adaptations.length?adaptationCard(plan.adaptations.at(-1)):''}</div>`;
  $('#adapt-plan')?.addEventListener('click',async()=>{const adaptation=adaptNextWeek(plan,store.state.attempts);store.update(s=>{s.plans[plan.id]=plan});await firebaseService.savePlan(currentUser.uid,plan);toast(`Đã ưu tiên: ${adaptation.prioritySkills.map(s=>skillLabels[s]||s).join(', ')||'duy trì cân bằng'}.`);renderRoadmap();});
}
function timelineItem(session,done){const isDone=done.has(session.id),current=nextSession()?.id===session.id;return `<article class="timeline-item ${isDone?'done':''} ${current?'current':''}"><span class="timeline-number">${isDone?icon('check'):session.order}</span><div class="timeline-main"><h3>${html(session.title)}</h3><p>${session.minutes} phút · ${(session.reasonCodes||[]).map(c=>reasonLabels[c]).filter(Boolean).join(' · ')}</p></div><a class="timeline-action" href="#/activity/${session.id}">${isDone?'Học lại':current?'Học ngay':'Xem'}</a></article>`}
function adaptationCard(a){return `<section class="card lesson-card" style="margin-top:24px"><span class="skill-tag">Điều chỉnh tuần ${a.week}</span><h2 style="margin-top:12px">Kế hoạch đã học từ kết quả của bạn</h2><p class="muted">Ưu tiên: ${a.prioritySkills.map(s=>skillLabels[s]||s).join(', ')||'giữ nhịp cân bằng'}. ${a.missedSessionIds.length?`${a.missedSessionIds.length} phiên chưa hoàn thành được giữ lại.`:'Không có phiên bị bỏ lỡ.'}</p></section>`}

function renderReview() {
  const items=Object.values(store.state.reviewItems).sort((a,b)=>a.nextReviewAt.localeCompare(b.nextReviewAt));
  $('#main-content').innerHTML=`<div class="page">${pageHeader('Ôn tập','Những điểm chưa vững sẽ quay lại theo nhịp 1–3–7 ngày.')}<div class="review-list">${items.length?items.map(item=>`<article class="card review-item"><div><span class="skill-tag">${skillLabels[item.skill]||item.skill}</span><h3>${html(item.prompt)}</h3><p>Lần ôn ${item.intervalIndex+1} · ${item.nextReviewAt<=today()?'Đến hạn hôm nay':`Tiếp theo ${item.nextReviewAt}`}</p><div class="mastery-bar"><span style="width:${Math.round(item.mastery*100)}%"></span></div></div><button class="btn btn-secondary review-now" data-id="${item.id}" ${item.nextReviewAt>today()?'disabled':''}>${item.nextReviewAt<=today()?'Đã ôn':'Chưa đến hạn'}</button></article>`).join(''):`<div class="empty-state"><h2>Chưa có mục cần ôn</h2><p>Lỗi sai từ bài học sẽ tự động xuất hiện tại đây.</p><a class="btn btn-primary" href="#/today">Học phiên tiếp theo</a></div>`}</div></div>`;
  $$('.review-now').forEach(button=>button.addEventListener('click',async()=>{const item=store.state.reviewItems[button.dataset.id];item.intervalIndex=Math.min(2,item.intervalIndex+1);const days=[1,3,7][item.intervalIndex];const date=new Date();date.setDate(date.getDate()+days);item.nextReviewAt=date.toISOString().slice(0,10);item.mastery=Math.min(1,item.mastery+.18);store.update(()=>{});await firebaseService.saveReview(currentUser.uid,item);toast('Đã ghi nhận lượt ôn.');renderReview();}));
}

function renderProgress() {
  const mastery=masteryBySkill(store.state.attempts),sessions=planSessions(),completed=sessions.filter(s=>store.completedIds.has(s.id)).length,totalMinutes=Object.values(store.state.studyDays).reduce((sum,d)=>sum+(d.totalMinutes||0),0),days=lastSevenDays();
  $('#main-content').innerHTML=`<div class="page">${pageHeader('Tiến độ','Theo dõi độ vững từng kỹ năng, không chỉ số bài đã mở.')}<div class="stats-grid"><div class="stat-card"><span>Phiên hoàn thành</span><strong>${completed}/${sessions.length}</strong></div><div class="stat-card"><span>Thời gian học</span><strong>${totalMinutes} phút</strong></div><div class="stat-card"><span>Độ chính xác</span><strong>${averageScore()}%</strong></div><div class="stat-card"><span>Diagnostic</span><strong>${store.activePlan.diagnostic.percentage}%</strong></div></div><div class="progress-layout"><section class="card chart-card"><h2>Mastery theo kỹ năng</h2><div class="skill-bars">${Object.keys(skillLabels).filter(k=>k!=='mixed').map(skill=>skillBar(skill,mastery[skill]||0)).join('')}</div></section><section class="card chart-card"><h2>7 ngày gần đây</h2><div class="week-bars">${days.map(day=>`<div class="day-bar"><i style="--h:${Math.min(100,(store.state.studyDays[day.iso]?.totalMinutes||0)*2.5)}%"></i><span>${day.label}</span></div>`).join('')}</div></section></div></div>`;
}
function skillBar(skill,value){return `<div class="skill-row"><span>${skillLabels[skill]}</span><div class="bar"><span style="width:${value}%"></span></div><strong>${value}%</strong></div>`}
function averageScore(){const attempts=store.state.attempts.filter(a=>!a.sessionComplete&&Number.isFinite(Number(a.score)));return attempts.length?Math.round(100*attempts.reduce((s,a)=>s+Number(a.score),0)/attempts.length):0}
function lastSevenDays(){const fmt=new Intl.DateTimeFormat('vi',{weekday:'short'});return Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return{iso:d.toISOString().slice(0,10),label:fmt.format(d)}})}

function renderSettings() {
  const settings=store.state.settings,keyPresent=!!geminiService.key;
  $('#main-content').innerHTML=`<div class="page">${pageHeader('Cài đặt','Quản lý giao diện, AI và tài khoản trên thiết bị này.')}<div class="settings-grid"><section class="card settings-section"><h2>Giao diện và học tập</h2><div class="setting-row"><div class="setting-copy"><strong>Chế độ tối</strong><small>Đồng bộ cài đặt giao diện lên tài khoản.</small></div><label class="switch"><input id="theme-switch" type="checkbox" ${settings.theme==='dark'?'checked':''}><span></span></label></div><div class="setting-row"><div class="setting-copy"><strong>Lịch hiện tại</strong><small>${store.activePlan.schedule.daysPerWeek} ngày/tuần · ${store.activePlan.schedule.minutesPerDay} phút/ngày</small></div><button id="new-goal" class="btn btn-secondary">Đổi mục tiêu</button></div></section><section class="card settings-section"><h2>Cài ứng dụng</h2><div class="setting-row"><div class="setting-copy"><strong>English Assistant trên màn hình chính</strong><small>Mở trong cửa sổ riêng và tiếp tục dùng nội dung đã tải khi mất mạng.</small></div><button class="btn btn-secondary" type="button" data-pwa-install>Cài đặt</button></div></section><section class="card settings-section"><h2>Gemini AI trên thiết bị</h2><p class="muted">Key không được gửi lên Firestore. Nếu bật ghi nhớ, key nằm trong localStorage của trình duyệt này.</p><div class="api-form"><input id="api-key" type="password" autocomplete="off" placeholder="Dán Gemini API key" value="${keyPresent?'••••••••••••':''}" aria-label="Gemini API key"><button id="load-models" class="btn btn-secondary">Tải model</button></div><label class="setting-row"><div class="setting-copy"><strong>Ghi nhớ trên thiết bị này</strong><small>Chỉ bật trên thiết bị cá nhân.</small></div><span class="switch"><input id="remember-key" type="checkbox" ${!!localStorage.getItem('ela_gemini_key')?'checked':''}><span></span></span></label><div class="model-row"><select id="model-select" aria-label="Gemini model"><option value="${html(geminiService.model)}">${geminiService.model?html(geminiService.model):'Tải danh sách model để chọn'}</option></select><button id="save-ai" class="btn btn-primary">Lưu AI</button></div><p id="ai-status" class="form-hint">${keyPresent?'API key đã được cấu hình trên thiết bị.':'Writing và speaking feedback cần API key.'}</p></section><section class="card settings-section"><h2>Tài khoản</h2><div class="setting-row"><div class="setting-copy"><strong>${html(store.state.profile.displayName)}</strong><small>${html(store.state.profile.email)}</small></div><button id="logout" class="btn btn-danger">${icon('logout')} Đăng xuất</button></div></section></div></div>`;
  refreshPwaInstall();
  $('#theme-switch').addEventListener('change',toggleTheme);$('#logout').addEventListener('click',()=>firebaseService.logout());$('#new-goal').addEventListener('click',newGoal);$('#load-models').addEventListener('click',loadModels);$('#save-ai').addEventListener('click',saveAiSettings);
}
function toggleTheme(){const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;store.update(s=>s.settings.theme=theme);firebaseService.saveSettings(currentUser.uid,store.state.settings).catch(()=>{});renderThemeIcon();}
function renderThemeIcon(){$('#mobile-theme').innerHTML=icon(document.documentElement.dataset.theme==='dark'?'sun':'moon')}
async function loadModels(){const keyInput=$('#api-key').value.trim(),key=keyInput&&!keyInput.startsWith('••')?keyInput:geminiService.key,status=$('#ai-status'),button=$('#load-models');button.disabled=true;status.textContent='Đang tải model...';try{const models=await geminiService.listModels(key);$('#model-select').innerHTML=models.map(m=>`<option value="${html(m.id)}" ${m.id===geminiService.model?'selected':''}>${html(m.name)}</option>`).join('');status.textContent=`Đã tìm thấy ${models.length} model hỗ trợ generateContent.`;if(keyInput&&!keyInput.startsWith('••'))$('#api-key').dataset.pendingKey=keyInput}catch(error){status.textContent=error.message}finally{button.disabled=false}}
function saveAiSettings(){const input=$('#api-key'),pending=input.dataset.pendingKey||(!input.value.startsWith('••')?input.value:'')||geminiService.key,model=$('#model-select').value;if(!pending||!model){$('#ai-status').textContent='Hãy nhập key, tải và chọn model.';return}geminiService.configure(pending,$('#remember-key').checked,model);$('#ai-status').textContent='Đã lưu cấu hình AI trên thiết bị này.';toast('Đã cập nhật Gemini.');}
async function newGoal(){if(!confirm('Lộ trình hiện tại sẽ được lưu vào lịch sử và bạn sẽ tạo lộ trình mới. Tiếp tục?'))return;store.update(s=>{s.onboardingComplete=false;s.currentPlanId=null});await firebaseService.upsertProfile(currentUser,false,null);$('#app-shell').hidden=true;showOnboarding();}

function renderActivity(sessionId) {
  const session=planSessions().find(s=>s.id===sessionId);if(!session){location.hash='#/today';return}activityStartedAt=Date.now();renderActivityStep(session,0,[]);
}
function renderActivityStep(session,index,results) {
  const activity=session.activities[index],pct=Math.round(index/session.activities.length*100);
  $('#main-content').innerHTML=`<div class="activity-page"><div class="activity-top"><a class="icon-btn" href="#/roadmap" aria-label="Quay lại">${icon('back')}</a><div class="activity-progress" aria-label="Tiến trình phiên học"><span style="width:${pct}%"></span></div><strong>${index+1}/${session.activities.length}</strong></div><article class="card activity-card"><span class="skill-tag">${skillLabels[activity.skill||session.skill]||session.skill}</span><h1>${html(activity.title||session.title)}</h1><div id="activity-body"></div></article></div>`;
  const body=$('#activity-body');
  if(activity.type==='flashcards')renderFlashcards(body,activity,()=>finishActivity(session,index,results,{score:1,answer:'reviewed'}));
  else if(['mcq','reading','listening'].includes(activity.type))renderChoice(body,activity,session,index,results);
  else if(activity.type==='fill')renderFill(body,activity,session,index,results);
  else if(activity.type==='reorder')renderReorder(body,activity,session,index,results);
  else if(['writing','short'].includes(activity.type))renderSubjective(body,activity,session,index,results);
  else if(activity.type==='speaking-live')renderSpeaking(body,activity,session,index,results);
}
function renderFlashcards(body,a,onDone){body.innerHTML=`<p class="lead">Chạm vào từng thẻ để xem nghĩa.</p><div class="activity-options">${a.cards.map(([front,back])=>`<button class="option-btn flashcard" data-front="${html(front)}" data-back="${html(back)}"><strong>${html(front)}</strong></button>`).join('')}</div><div class="activity-actions"><button id="flash-done" class="btn btn-primary">Đã xem tất cả ${icon('arrow')}</button></div>`;$$('.flashcard',body).forEach(btn=>btn.addEventListener('click',()=>{btn.innerHTML=btn.dataset.flipped?`<strong>${btn.dataset.front}</strong>`:`<strong>${btn.dataset.front}</strong><br><span class="muted">${btn.dataset.back}</span>`;btn.dataset.flipped=btn.dataset.flipped?'':'1'}));$('#flash-done').addEventListener('click',onDone)}
function renderChoice(body,a,session,index,results){body.innerHTML=`${a.passage?`<div class="prompt-box">${html(a.passage)}</div>`:''}${a.type==='listening'?`<button id="listen-btn" class="btn btn-secondary">${icon('volume')} Nghe đoạn hội thoại</button>`:''}<div class="prompt-box">${html(a.prompt)}</div><div class="activity-options">${a.options.map((o,i)=>`<button class="option-btn" data-value="${i}">${html(o)}</button>`).join('')}</div><div id="answer-feedback"></div><div class="activity-actions"><button id="check-answer" class="btn btn-primary" disabled>Kiểm tra</button></div>`;let selected=null,checked=null;$$('.option-btn',body).forEach(btn=>btn.addEventListener('click',()=>{if(checked)return;$$('.option-btn',body).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');selected=Number(btn.dataset.value);$('#check-answer').disabled=false}));$('#listen-btn')?.addEventListener('click',()=>speakText(a.text));$('#check-answer').addEventListener('click',()=>{if(checked){finishActivity(session,index,results,checked);return}const ok=selected===a.answer;checked={score:ok?1:0,answer:selected};$$('.option-btn',body).forEach(btn=>{btn.disabled=true;if(Number(btn.dataset.value)===a.answer)btn.classList.add('correct');else if(btn.classList.contains('selected'))btn.classList.add('wrong')});showAnswerFeedback(a,ok);$('#check-answer').textContent='Tiếp tục';})}
function renderFill(body,a,session,index,results){body.innerHTML=`<div class="prompt-box">${html(a.prompt)}</div><label class="field"><span>Câu trả lời</span><input id="fill-answer" autocomplete="off"></label><div id="answer-feedback"></div><div class="activity-actions"><button id="check-answer" class="btn btn-primary">Kiểm tra</button></div>`;let checked=null;$('#check-answer').addEventListener('click',()=>{if(checked){finishActivity(session,index,results,checked);return}const value=$('#fill-answer').value.trim(),ok=normalize(value)===normalize(a.answer);checked={score:ok?1:0,answer:value};showAnswerFeedback(a,ok,`Đáp án: ${a.answer}`);$('#fill-answer').disabled=true;$('#check-answer').textContent='Tiếp tục';})}
function renderReorder(body,a,session,index,results){let picked=[],checked=null;body.innerHTML=`<div class="prompt-box">${html(a.prompt)}</div><div id="constructed" class="constructed-answer"><span class="muted">Chọn các cụm từ theo thứ tự</span></div><div class="reorder-bank">${a.words.map((w,i)=>`<button class="word-chip" data-index="${i}">${html(w)}</button>`).join('')}</div><div id="answer-feedback"></div><div class="activity-actions"><button id="reset-order" class="btn btn-secondary">Làm lại</button><button id="check-answer" class="btn btn-primary" disabled>Kiểm tra</button></div>`;const update=()=>{$('#constructed').innerHTML=picked.length?picked.map(i=>`<button class="word-chip" data-picked="${i}">${html(a.words[i])}</button>`).join(''):'<span class="muted">Chọn các cụm từ theo thứ tự</span>';$$('[data-picked]').forEach(b=>b.addEventListener('click',()=>{if(checked)return;picked=picked.filter(i=>i!==Number(b.dataset.picked));$(`.word-chip[data-index="${b.dataset.picked}"]`).classList.remove('used');update()}));$('#check-answer').disabled=!picked.length};$$('.reorder-bank .word-chip').forEach(b=>b.addEventListener('click',()=>{if(!checked&&!picked.includes(Number(b.dataset.index))){picked.push(Number(b.dataset.index));b.classList.add('used');update()}}));$('#reset-order').addEventListener('click',()=>{if(checked)return;picked=[];$$('.reorder-bank .word-chip').forEach(b=>b.classList.remove('used'));update()});$('#check-answer').addEventListener('click',()=>{if(checked){finishActivity(session,index,results,checked);return}const value=picked.map(i=>a.words[i]).join(' ').replace(/\s+([,.?])/g,'$1'),ok=normalize(value)===normalize(a.answer);checked={score:ok?1:0,answer:value};showAnswerFeedback(a,ok,`Đáp án: ${a.answer}`);$('#check-answer').textContent='Tiếp tục';})}
function renderSubjective(body,a,session,index,results){body.innerHTML=`<div class="prompt-box">${html(a.prompt)}</div><label class="field"><span>Câu trả lời của bạn</span><textarea id="subjective-answer" class="writing-area"></textarea></label><div id="ai-result"></div><div class="activity-actions"><button id="submit-subjective" class="btn btn-primary">${geminiService.key&&geminiService.model?`${icon('spark')} Nhận phản hồi AI`:'Xem gợi ý & tự đánh giá'}</button></div>`;let ready=null;$('#submit-subjective').addEventListener('click',async()=>{if(ready){finishActivity(session,index,results,ready);return}const answer=$('#subjective-answer').value.trim();if(answer.length<8){toast('Hãy viết câu trả lời trước.');return}const btn=$('#submit-subjective');btn.disabled=true;let score=.7,feedback=null;try{if(geminiService.key&&geminiService.model){btn.textContent='Đang phân tích...';feedback=await geminiService.evaluate({type:'writing',prompt:a.prompt,answer});score=Object.values(feedback.scores).reduce((x,y)=>x+y,0)/(Object.keys(feedback.scores).length*9);renderAiFeedback(feedback)}else{$('#ai-result').innerHTML=`<div class="feedback-box"><strong>Gợi ý tham khảo</strong><p>${html(a.sample||'Kiểm tra cấu trúc, độ rõ ý và từ vựng của câu trả lời.')}</p></div>`}ready={score,answer,feedback};btn.disabled=false;btn.textContent='Tiếp tục'}catch(error){$('#ai-result').innerHTML=`<div class="inline-alert error">${html(error.message)} <button id="retry-ai" class="btn btn-secondary">Thử lại</button></div>`;$('#retry-ai').onclick=()=>btn.click();btn.disabled=false}})}
function showAnswerFeedback(a,ok,extra=''){const box=$('#answer-feedback');box.innerHTML=`<div class="feedback-box"><strong>${ok?'Chính xác':'Chưa đúng'}</strong><p>${html(extra||a.explanation||'')}</p>${a.explanation&&extra?`<p class="muted">${html(a.explanation)}</p>`:''}</div>`}
function renderAiFeedback(f){$('#ai-result').innerHTML=`<div class="ai-feedback"><h3>Phản hồi AI</h3><div class="score-grid">${Object.entries(f.scores).map(([k,v])=>`<div class="score-box"><strong>${v}</strong><small>${html(k)}</small></div>`).join('')}</div>${f.summary?`<p>${html(f.summary)}</p>`:''}<strong>Cần cải thiện</strong><ul>${f.improvements.map(x=>`<li>${html(x)}</li>`).join('')}</ul>${f.rewrite?`<strong>Gợi ý viết lại</strong><div class="prompt-box">${html(f.rewrite)}</div>`:''}</div>`}
function normalize(value){return String(value).trim().toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ').replace(/\s+([,.?])/g,'$1')}
function speakText(text){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=.9;speechSynthesis.speak(utterance)}

async function finishActivity(session,index,results,result) {
  const a=session.activities[index],attempt=buildAttempt(session,a,result);results.push(attempt);store.recordAttempt(attempt);await firebaseService.saveAttempt(currentUser.uid,attempt).catch(()=>{});if(attempt.reviewItem)firebaseService.saveReview(currentUser.uid,attempt.reviewItem).catch(()=>{});
  if(index<session.activities.length-1){renderActivityStep(session,index+1,results);return}
  const completion=store.completeSession(session.id,Math.max(1,Math.round((Date.now()-activityStartedAt)/60000)));await firebaseService.saveAttempt(currentUser.uid,completion).catch(()=>{});const day=store.state.studyDays[today()];firebaseService.saveStudyDay(currentUser.uid,day).catch(()=>{});
  if(session.order===5&&!store.activePlan.adaptations.length){adaptNextWeek(store.activePlan,store.state.attempts);store.update(()=>{});firebaseService.savePlan(currentUser.uid,store.activePlan).catch(()=>{});}
  renderCompletion(session,results);
}
function buildAttempt(session,a,result){const now=new Date(),score=Number(result.score||0),id=`${a.id}-${now.getTime()}`;let reviewItem=null;if(score<.8&&a.type!=='writing'&&a.type!=='short'&&a.type!=='speaking-live'){const old=store.state.reviewItems[a.id],intervalIndex=old?.intervalIndex||0,date=new Date();date.setDate(date.getDate()+[1,3,7][intervalIndex]);reviewItem={id:a.id,skill:a.skill||session.skill,prompt:a.prompt||a.title,mastery:Math.max(0,score),intervalIndex,nextReviewAt:date.toISOString().slice(0,10),updatedAt:now.toISOString()}}return{id,sessionId:session.id,activityId:a.id,type:a.type,skill:a.skill||session.skill,answer:result.answer,score,feedback:result.feedback||null,reviewItem,date:today(),durationSeconds:Math.round((Date.now()-activityStartedAt)/1000),updatedAt:now.toISOString()}}
function renderCompletion(session,results){const score=Math.round(100*results.reduce((s,r)=>s+r.score,0)/results.length);$('#main-content').innerHTML=`<div class="activity-page"><article class="card activity-card" style="text-align:center"><span class="logo-mark" style="margin:0 auto 20px">${icon('check')}</span><div class="eyebrow">PHIÊN HOÀN THÀNH</div><h1>${score}% chính xác</h1><p class="lead" style="margin-inline:auto">${score>=80?'Bạn đang nắm rất tốt nội dung hôm nay.':score>=60?'Nền tảng ổn. Những điểm sai đã được đưa vào Ôn tập.':'Đừng lo — app đã lưu những điểm cần củng cố.'}</p><div class="activity-actions" style="justify-content:center"><a href="#/today" class="btn btn-primary">Về Hôm nay</a><a href="#/review" class="btn btn-secondary">Xem ôn tập</a></div></article></div>`}

async function renderSpeaking(body,a,session,index,results) {
  body.innerHTML=`<div class="speaking-stage"><div class="inline-alert info">Beta · Tối đa 10 phút · Transcript được lưu, audio không được lưu.</div><p class="lead" style="margin-inline:auto">${html(a.scenario)}</p><button id="connect-live" class="btn btn-primary">Kết nối hội thoại</button><button id="mic-live" class="mic-button" hidden aria-label="Bật micro">${icon('mic')}</button><p id="speaking-status" class="speaking-status">Cần kết nối Internet và quyền micro.</p><div id="live-transcript" class="transcript-panel" aria-live="polite"></div><div class="activity-actions"><button id="finish-live" class="btn btn-secondary" hidden>Kết thúc & nhận feedback</button></div></div>`;
  $('#connect-live').addEventListener('click',async()=>{const btn=$('#connect-live');btn.disabled=true;btn.textContent='Đang kết nối...';try{const models=await geminiService.listLiveModels();if(!models.length)throw new Error('API key này không có model hỗ trợ Live API.');liveService=new LiveSpeakingService();bindLiveEvents(liveService);await liveService.connect({apiKey:geminiService.key,model:models[0].name,scenario:a.scenario});btn.hidden=true;$('#mic-live').hidden=false;$('#finish-live').hidden=false}catch(error){$('#speaking-status').textContent=error.message;btn.disabled=false;btn.textContent='Thử kết nối lại'}});
  let listening=false;$('#mic-live').addEventListener('click',async()=>{try{if(listening){liveService.stopMicrophone();listening=false;$('#mic-live').classList.remove('active')}else{await liveService.startMicrophone();listening=true;$('#mic-live').classList.add('active')}}catch(error){$('#speaking-status').textContent=`Không thể dùng micro: ${error.message}`}});
  let ready=null;$('#finish-live').addEventListener('click',async()=>{if(ready){finishActivity(session,index,results,ready);return}const transcript=liveService?.stop()||[];liveService=null;const text=transcript.map(t=>`${t.role}: ${t.text}`).join('\n');if(!text){toast('Chưa có hội thoại để đánh giá.');return}const btn=$('#finish-live');btn.disabled=true;btn.textContent='Đang chấm transcript...';let feedback=null,score=.7;try{feedback=await geminiService.evaluate({type:'speaking',prompt:a.scenario,answer:'',transcript:text});score=Object.values(feedback.scores).reduce((x,y)=>x+y,0)/(Object.keys(feedback.scores).length*9);renderAiFeedback(feedback)}catch(error){toast(error.message)}const record={id:`speaking-${Date.now()}`,scenario:a.title,transcript,feedback,durationSeconds:Math.round((Date.now()-activityStartedAt)/1000),createdAt:new Date().toISOString()};store.update(s=>s.speakingSessions.push(record));firebaseService.saveSpeaking(currentUser.uid,record).catch(()=>{});ready={score,answer:text,feedback};btn.disabled=false;btn.textContent='Tiếp tục';});
}
function bindLiveEvents(service){service.addEventListener('status',e=>{$('#speaking-status').textContent=e.detail.message});service.addEventListener('error',e=>{$('#speaking-status').textContent=e.detail.message});service.addEventListener('transcript',e=>{$('#live-transcript').innerHTML=e.detail.transcript.map(t=>`<div class="bubble ${t.role}">${html(t.text)}</div>`).join('');$('#live-transcript').scrollTop=$('#live-transcript').scrollHeight})}

function registerServiceWorker(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('./sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)toast('Có phiên bản mới. Tải lại trang để cập nhật.')})})}).catch(()=>{})}

renderThemeIcon();
init().catch(error=>showAuthError(`Không thể khởi động ứng dụng: ${error.message}`));
