import { firebaseService, hasCloudLearningData } from './services/firebase.js?v=9';
import { geminiService } from './services/gemini.js?v=6';
import { LiveSpeakingService } from './services/live-speaking.js?v=5';
import { initPwaInstall, refreshPwaInstall } from './services/pwa-install.js?v=1';
import { store } from './core/store.js?v=3';
import { scoreDiagnostic, createPlan, adaptNextWeek, masteryBySkill, calculateStreak, extendCurriculum, upgradePlan, personalizeSession } from './core/plan-engine.js?v=8';
import { hydrateGrammarSession, grammarTopicById, grammarPathProgress } from './core/grammar-engine.js?v=1';
import { expandLearningSession } from './core/lesson-engine.js?v=1';

const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const html = (value='') => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const today = () => new Date().toISOString().slice(0,10);
const skillLabels = { vocabulary:'Từ vựng',grammar:'Ngữ pháp',reading:'Reading',writing:'Writing',listening:'Listening',speaking:'Speaking',mixed:'Tổng hợp' };
const reasonLabels = { CURRICULUM_CORE:'Nội dung cốt lõi',GRAMMAR_SPINE:'Grammar Spine A1–B2',PROFESSIONAL_VOCABULARY:'Từ vựng theo ngành nghề',SELF_REPORTED_WEAK:'Kỹ năng bạn muốn cải thiện',DIAGNOSTIC_GAP:'Khoảng trống từ bài đầu vào',LOW_MASTERY:'Cần củng cố theo kết quả',MISSED_SESSIONS:'Bài chưa hoàn thành',WEEKLY_REBALANCE:'Điều chỉnh cuối tuần' };
let curriculum, professions, diagnostic, grammarMap, currentUser, currentStep=1, liveService=null, activityStartedAt=0, accountMenuTrigger=null, logoutReturnTarget=null, cloudSyncPromise=null, lastCloudSyncAt=0, roadmapVisibleWeek=0, aiCoachMode='chat', aiCoachMessages=[];
const LIVE_VOLUME_KEY='ela_live_output_volume';

function toast(message) {
  const node=document.createElement('div');node.className='toast';node.textContent=message;$('#toast-region').append(node);setTimeout(()=>node.remove(),4200);
}
function icon(name) {
  const paths={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',moon:'<path d="M20.5 14.5A8 8 0 0 1 9.5 3.5 8.5 8.5 0 1 0 20.5 14.5Z"/>',arrow:'<path d="m9 18 6-6-6-6"/>',back:'<path d="m15 18-6-6 6-6"/>',send:'<path d="m22 2-7 20-4-9-9-4 20-7Z"/><path d="M22 2 11 13"/>',play:'<path d="m8 5 11 7-11 7V5Z"/>',mic:'<path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2M12 19v3"/>',check:'<path d="m5 12 4 4L19 6"/>',volume:'<path d="M11 5 6 9H2v6h4l5 4V5ZM15 9a4 4 0 0 1 0 6M18 6a8 8 0 0 1 0 12"/>',spark:'<path d="m12 3 1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5L12 3ZM5 15l.8 2.2L8 18l-2.2.8L5 21l-.8-2.2L2 18l2.2-.8L5 15Z"/>',logout:'<path d="M10 17l5-5-5-5M15 12H3M14 3h5a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-5"/>'};return `<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]||''}</svg>`;
}

async function init() {
  initPwaInstall({notify:toast});
  const [baseCurriculum,roadmap,professionData,diagnosticData,grammarData]=await Promise.all([fetch('./data/curriculum.json').then(r=>r.json()),fetch('./data/roadmap.json').then(r=>r.json()),fetch('./data/professions.json').then(r=>r.json()),fetch('./data/diagnostic.json').then(r=>r.json()),fetch('./data/grammar-map.json').then(r=>r.json())]);curriculum=extendCurriculum(baseCurriculum,roadmap);professions=professionData.industries||[];diagnostic=diagnosticData;grammarMap=grammarData;
  bindGlobal();renderDiagnostic();
  firebaseService.onAuth(handleAuth);
  try { await firebaseService.init(); firebaseService.restoreDemo(); } catch(error) { showAuthError(error.message); }
  if(firebaseService.demo){$('#demo-login-btn').hidden=false;$('#auth-hint').textContent='Firebase chưa cấu hình. Dùng demo để kiểm tra toàn bộ luồng trên thiết bị này.';}
  updateNetwork();registerServiceWorker();
}

function bindGlobal() {
  $('#google-login-btn').onclick=async()=>{setLoginBusy(true);try{await firebaseService.login()}catch(error){showAuthError(error.message)}finally{setLoginBusy(false)} };
  $('#demo-login-btn').onclick=()=>firebaseService.loginDemo();
  $('#onboarding-logout').onclick=event=>requestLogout(event.currentTarget);
  $('#step-next').onclick=nextStep;$('#step-back').onclick=previousStep;$('#onboarding-form').onsubmit=submitOnboarding;
  $('[name="daysPerWeek"]').addEventListener('input',e=>$('#days-output').value=`${e.target.value} ngày`);
  $$('[name="track"]').forEach(input=>input.addEventListener('change',updateTrackFields));
  $('#industry-select').addEventListener('change',updateProfessionFields);
  window.addEventListener('hashchange',route);window.addEventListener('online',()=>{updateNetwork();syncCloudState(true)});window.addEventListener('offline',updateNetwork);
  document.addEventListener('click',handleAccountMenuClick);
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#account-menu').hidden)closeAccountMenu(true)});
  $('#account-refresh').addEventListener('click',()=>window.location.reload());
  $('#account-theme').addEventListener('click',()=>{toggleTheme();closeAccountMenu()});
  $('#account-logout').addEventListener('click',()=>{const returnTarget=accountMenuTrigger;closeAccountMenu();requestLogout(returnTarget)});
  $('#logout-cancel').addEventListener('click',()=>$('#logout-dialog').close('cancel'));
  $('#logout-confirm').addEventListener('click',confirmLogout);
  $('#logout-dialog').addEventListener('close',()=>{logoutReturnTarget?.focus();logoutReturnTarget=null});
  window.addEventListener('beforeunload',()=>liveService?.stop());document.addEventListener('visibilitychange',()=>{if(document.hidden&&liveService)liveService.stopMicrophone();else if(!document.hidden)syncCloudState(true)});
}

function setLoginBusy(value){$('#google-login-btn').disabled=value;$('#google-login-btn').lastChild.textContent=value?' Đang đăng nhập...':' Tiếp tục với Google';}
function showAuthError(message){$('#auth-error').hidden=false;$('#auth-error').textContent=message;}
function updateNetwork(){const offline=!navigator.onLine;$('#network-banner').hidden=!offline;document.body.classList.toggle('is-offline',offline);}
function requireCloudConnection(){if(firebaseService.demo||navigator.onLine)return true;toast('Cần kết nối Internet để lưu dữ liệu học lên Firestore.');return false;}

async function handleAuth(user) {
  currentUser=user;
  if(!user){$('#auth-screen').hidden=false;$('#onboarding-screen').hidden=true;$('#app-shell').hidden=true;return;}
  $('#auth-error').hidden=true;
  const profile={displayName:user.displayName||'Học viên',email:user.email||'',photoURL:user.photoURL||''};
  const legacyLocal=firebaseService.demo?null:store.readLocal(user.uid);
  store.load(user.uid,profile,{persistLocally:firebaseService.demo});
  if(!firebaseService.demo){
    try{
      let remote=await firebaseService.loadUserData(user.uid);
      if(!hasCloudLearningData(remote)&&hasCloudLearningData(legacyLocal)){
        await firebaseService.migrateLocalState(user,legacyLocal);
        remote=await firebaseService.loadUserData(user.uid);
        toast('Đã chuyển dữ liệu học cũ lên Firestore.');
      }
      store.mergeRemote(remote);store.clearLocal(user.uid);lastCloudSyncAt=Date.now();if(store.activePlan&&upgradePlan(store.activePlan,curriculum,grammarMap)){store.update(state=>{state.plans[store.activePlan.id]=store.activePlan});await firebaseService.savePlan(user.uid,store.activePlan)}
    }catch(error){showAuthError(`Không thể tải dữ liệu học từ Firestore. Hãy kiểm tra mạng rồi tải lại trang. ${error.message}`);$('#auth-screen').hidden=false;$('#onboarding-screen').hidden=true;$('#app-shell').hidden=true;return;}
  }
  await firebaseService.upsertProfile(user,store.state.onboardingComplete,store.state.currentPlanId).catch(()=>{});
  $('#auth-screen').hidden=true;
  renderProfile();
  if(store.state.onboardingComplete&&store.activePlan)showApp();else showOnboarding();
}

function syncCloudState(refreshView=false){
  if(firebaseService.demo||!currentUser||!navigator.onLine||cloudSyncPromise||Date.now()-lastCloudSyncAt<15000)return cloudSyncPromise;
  cloudSyncPromise=firebaseService.loadUserData(currentUser.uid).then(remote=>{store.mergeRemote(remote);lastCloudSyncAt=Date.now();if(refreshView&&!$('#app-shell').hidden&&!location.hash.startsWith('#/activity/')){renderProfile();route()}}).catch(error=>toast(`Không thể đồng bộ dữ liệu mới: ${error.message}`)).finally(()=>{cloudSyncPromise=null});
  return cloudSyncPromise;
}

function showOnboarding(){currentStep=1;$('#onboarding-screen').hidden=false;$('#app-shell').hidden=true;renderStep();}
function showApp(){ $('#onboarding-screen').hidden=true;$('#app-shell').hidden=false;if(!location.hash||location.hash==='#/')location.hash='#/today';route(); }
function renderProfile(){const p=store.state.profile||{},name=p.displayName||'Học viên',avatar=p.photoURL?`<img src="${html(p.photoURL)}" alt="">`:`<span class="avatar-fallback">${html(name[0])}</span>`,details=`<div><strong>${html(name)}</strong><small>${html(p.email||'Demo local')}</small></div>`;$('#sidebar-profile').innerHTML=`<button class="profile-trigger" type="button" data-account-trigger aria-haspopup="menu" aria-expanded="false">${avatar}${details}<svg aria-hidden="true" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></button>`;$('#mobile-account').innerHTML=avatar;$('#mobile-account').setAttribute('aria-label',`Mở menu tài khoản của ${name}`);$('#account-menu-profile').innerHTML=`${avatar}${details}`;renderAccountTheme();}

function handleAccountMenuClick(event){const trigger=event.target.closest('[data-account-trigger]');if(trigger){event.preventDefault();toggleAccountMenu(trigger);return}if(event.target.closest('[data-account-menu-close]')){closeAccountMenu();return}if(!event.target.closest('#account-menu'))closeAccountMenu();}
function toggleAccountMenu(trigger){const menu=$('#account-menu'),willOpen=menu.hidden;menu.hidden=!willOpen;accountMenuTrigger=willOpen?trigger:null;$$('[data-account-trigger]').forEach(button=>button.setAttribute('aria-expanded',String(willOpen)));if(willOpen)requestAnimationFrame(()=>menu.querySelector('[role="menuitem"]')?.focus());}
function closeAccountMenu(restoreFocus=false){const menu=$('#account-menu');if(!menu)return;menu.hidden=true;$$('[data-account-trigger]').forEach(button=>button.setAttribute('aria-expanded','false'));if(restoreFocus)accountMenuTrigger?.focus();accountMenuTrigger=null;}
function renderAccountTheme(){const button=$('#account-theme');if(!button)return;const dark=document.documentElement.dataset.theme==='dark';button.innerHTML=`${icon(dark?'sun':'moon')}<span>${dark?'Chuyển sang giao diện sáng':'Chuyển sang giao diện tối'}</span>`;}
function requestLogout(returnTarget){logoutReturnTarget=returnTarget||document.activeElement;const dialog=$('#logout-dialog');if(!dialog.open)dialog.showModal();}
async function confirmLogout(){const button=$('#logout-confirm');button.disabled=true;button.textContent='Đang đăng xuất...';try{await firebaseService.logout();$('#logout-dialog').close('logout')}catch(error){toast(`Không thể đăng xuất: ${error.message}`)}finally{button.disabled=false;button.textContent='Đăng xuất'}}

function renderDiagnostic() {
  $('#diagnostic-questions').innerHTML=diagnostic.map((q,index)=>`<article class="question-card"><fieldset><legend>${index+1}. ${html(q.prompt)}</legend><div class="answer-options">${q.options.map((option,i)=>`<label><input type="radio" name="diagnostic-${q.id}" value="${i}" required><span>${html(option)}</span></label>`).join('')}</div></fieldset></article>`).join('');
}
function updateTrackFields(){const track=$('[name="track"]:checked')?.value;$('#ielts-fields').hidden=track!=='ielts';$('#communication-context-field').hidden=track!=='communication';}
function updateProfessionFields(){const custom=$('#industry-select').value==='other',field=$('#custom-industry-field'),input=$('#custom-industry');field.hidden=!custom;input.required=custom;if(!custom)input.value='';}
function renderStep(){$$('.wizard-step').forEach(step=>step.hidden=Number(step.dataset.step)!==currentStep);$('#step-progress-label').textContent=`Bước ${currentStep} / 4`;$('#step-progress-fill').style.width=`${currentStep*25}%`;$('#step-back').hidden=currentStep===1;$('#step-next').hidden=currentStep===4;$('#create-plan').hidden=currentStep!==4;$('#form-error-summary').hidden=true;updateTrackFields();updateProfessionFields();$('.wizard-step:not([hidden]) h1')?.focus?.();}
function validateStep(){const step=$(`.wizard-step[data-step="${currentStep}"]`);const inputs=$$('input,select,textarea',step);for(const input of inputs){if(!input.checkValidity()){showFormError(input.validationMessage||'Hãy hoàn thành thông tin bắt buộc.',input);return false;}}if(currentStep===3){for(const q of diagnostic){if(!$(`[name="diagnostic-${q.id}"]:checked`)){showFormError(`Hãy trả lời đủ ${diagnostic.length} câu diagnostic.`,$(`[name="diagnostic-${q.id}"]`));return false;}}}return true;}
function showFormError(message,input){const box=$('#form-error-summary');box.textContent=message;box.hidden=false;box.focus();input?.focus();}
function nextStep(){if(!validateStep())return;currentStep=Math.min(4,currentStep+1);renderStep();window.scrollTo({top:0});}
function previousStep(){currentStep=Math.max(1,currentStep-1);renderStep();window.scrollTo({top:0});}

async function submitOnboarding(event) {
  event.preventDefault();if(!validateStep()||!requireCloudConnection())return;const button=$('#create-plan');button.disabled=true;button.textContent='Đang tạo lộ trình...';
  try { const formData=new FormData(event.currentTarget),result=scoreDiagnostic(diagnostic,formData),plan=createPlan({formData,diagnostic:result,curriculum,professions,grammarMap});await Promise.all([firebaseService.savePlan(currentUser.uid,plan),firebaseService.upsertProfile(currentUser,true,plan.id)]);store.setPlan(plan);toast(`Đã tạo lộ trình ${plan.track==='ielts'?'IELTS':'Giao tiếp'} với Grammar Spine và từ vựng ${plan.professionalProfile.industryLabel}.`);showApp(); }
  catch(error){showFormError(error.message)}finally{button.disabled=false;button.textContent='Tạo lộ trình của tôi';}
}

function route() {
  if(!currentUser||$('#app-shell').hidden)return;
  if(liveService){liveService.stop();liveService=null;coachListening=false;}
  const parts=(location.hash.replace(/^#\//,'')||'today').split('/'),name=parts[0];
  $$('[data-route]').forEach(link=>link.classList.toggle('active',link.dataset.route===name));
  const content=$('#main-content');content.innerHTML='';
  if(name==='activity')renderActivity(parts[1]);else if(name==='roadmap')renderRoadmap();else if(name==='ai-coach')renderAiCoach();else if(name==='review')renderReview();else if(name==='progress')renderProgress();else if(name==='settings')renderSettings();else renderToday();
  updateReviewBadge();content.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});
}
function planSessions(){
  const plan=store.activePlan;if(!plan)return[];
  const sourceById=new Map((curriculum?.tracks?.[plan.track]||[]).map(session=>[session.id,session]));
  return [...(plan.sessions||[])].map(assignment=>{let session=personalizeSession({...sourceById.get(assignment.id),...assignment},plan,professions);if(session.grammarTopicId){const key=grammarLessonKey(plan.id,session.grammarTopicId);session=hydrateGrammarSession(session,plan,grammarMap,store.state.grammarLessons?.[key])}return expandLearningSession(session)}).sort((a,b)=>a.order-b.order);
}
function grammarLessonKey(planId,topicId){return `${planId}_${topicId}`.replace(/[^a-zA-Z0-9_-]/g,'_')}
function nextSession(){const done=store.completedIds;return planSessions().find(s=>!done.has(s.id))||planSessions().at(-1)}
function progressPercent(){const sessions=planSessions();return sessions.length?Math.round(100*sessions.filter(s=>store.completedIds.has(s.id)).length/sessions.length):0}
function dueReviews(){return Object.values(store.state.reviewItems).filter(item=>item.nextReviewAt<=today())}
function updateReviewBadge(){const count=dueReviews().length,b=$('#review-badge');b.textContent=count;b.hidden=!count;}
function pageHeader(title,description,actions=''){return `<header class="page-header"><div><div class="eyebrow">YOUR ENGLISH JOURNEY</div><h1>${title}</h1>${description?`<p class="lead">${description}</p>`:''}</div><div class="header-actions">${actions}</div></header>`}

function renderToday() {
  const plan=store.activePlan,session=nextSession(),progress=progressPercent(),streak=calculateStreak(store.state.studyDays),reviews=dueReviews().length;
  $('#main-content').innerHTML=`<div class="page"><section class="hero-panel"><div><div class="eyebrow" style="color:#99f6e4">${plan.track==='ielts'?'IELTS PATH':'COMMUNICATION PATH'} · TUẦN ${plan.weekIndex}</div><h1>${greeting()}, ${html((store.state.profile?.displayName||'bạn').split(' ')[0])}.<br>Tiến thêm một bước hôm nay.</h1><p>${session?`Phiên tiếp theo tập trung vào ${skillLabels[session.skill]||session.skill}${plan.professionalProfile?`, kèm từ vựng ${html(plan.professionalProfile.industryLabel)}`:''}.`:'Bạn đã hoàn thành lộ trình mẫu.'}</p>${session?`<a class="btn" href="#/activity/${session.id}">${icon('play')} Bắt đầu · ${session.minutes} phút</a>`:''}</div><div class="hero-score" style="--progress:${progress}%"><span>${progress}%<small>HOÀN THÀNH</small></span></div></section>
  <div class="stats-grid"><div class="stat-card"><span>Chuỗi học</span><strong>${streak} ngày</strong></div><div class="stat-card"><span>Đã hoàn thành</span><strong>${store.completedIds.size}/${sessionsCount(plan)}</strong></div><div class="stat-card"><span>Cần ôn hôm nay</span><strong>${reviews} mục</strong></div><div class="stat-card"><span>Nhịp học</span><strong>${plan.schedule.minutesPerDay} phút</strong></div></div>
  <div class="section-heading"><h2>Kế hoạch hôm nay</h2><a href="#/roadmap">Xem lộ trình</a></div><div class="today-grid">${sessionCard(session)}<aside class="card review-card"><span class="skill-tag">Ôn tập thông minh</span><p class="review-count">${reviews}</p><h3>${reviews?'mục đang chờ bạn':'Bạn đã ôn xong'}</h3><p class="muted">Các lỗi sai quay lại theo nhịp 1–3–7 ngày.</p><a href="#/review" class="btn btn-secondary">Mở ôn tập</a></aside></div></div>`;
}
function greeting(){const h=new Date().getHours();return h<11?'Chào buổi sáng':h<18?'Chào buổi chiều':'Chào buổi tối'}
function sessionsCount(plan){return plan.totalSessions||plan.sessions.length}
function sessionCard(session){if(!session)return `<div class="card empty-state"><h2>Hoàn thành xuất sắc</h2><p>Bạn đã kết thúc chu kỳ hiện tại. Hãy xem Tiến độ để chuẩn bị chu kỳ tiếp theo.</p></div>`;return `<article class="card lesson-card"><div class="lesson-card-top"><span class="skill-tag">${skillLabels[session.skill]||session.skill}</span><span class="status-pill">Phiên ${session.order}/${sessionsCount(store.activePlan)}</span></div><h3>${html(session.title)}</h3><p class="muted">${html(session.reason)}</p><div class="meta-row"><span>Tuần ${session.week}</span><span>${session.minutes} phút</span><span>${session.activities.length} hoạt động</span><span>${html(session.level)}</span></div><a class="btn btn-primary" href="#/activity/${session.id}">${icon('play')} Bắt đầu phiên học</a></article>`}

function renderRoadmap() {
  const plan=store.activePlan,done=store.completedIds,total=plan.totalWeeks||Math.max(...plan.sessions.map(s=>s.week));roadmapVisibleWeek=Math.min(total,Math.max(1,roadmapVisibleWeek||plan.weekIndex));const weekSessions=planSessions().filter(s=>s.week===roadmapVisibleWeek),phase=weekSessions[0]?.phase||'Nền tảng';
  $('#main-content').innerHTML=`<div class="page">${pageHeader(`Lộ trình ${total} tuần`,`${plan.track==='ielts'?'IELTS':'Giao tiếp'} · ${plan.schedule.daysPerWeek} ngày/tuần · ${plan.schedule.minutesPerDay} phút/ngày`)}<div class="roadmap-summary card"><div><span class="skill-tag">${html(phase)}</span><h2>Tuần ${roadmapVisibleWeek}: ${html(weekSessions[0]?.reason||'Kế hoạch cá nhân')}</h2><p class="muted">${weekSessions.filter(s=>done.has(s.id)).length}/${weekSessions.length} phiên hoàn thành</p></div><div class="week-switcher"><button id="week-prev" class="btn btn-secondary" ${roadmapVisibleWeek===1?'disabled':''} aria-label="Tuần trước">${icon('back')}</button><label><span>Chọn tuần</span><select id="week-select">${Array.from({length:total},(_,i)=>`<option value="${i+1}" ${i+1===roadmapVisibleWeek?'selected':''}>Tuần ${i+1}</option>`).join('')}</select></label><button id="week-next" class="btn btn-secondary" ${roadmapVisibleWeek===total?'disabled':''} aria-label="Tuần sau">${icon('arrow')}</button></div></div><div class="inline-alert info">Mỗi tuần có mục tiêu riêng. Tuần kế tiếp được điều chỉnh từ kết quả, bài bỏ lỡ và kỹ năng còn yếu.</div><div class="timeline"><section class="timeline-week">${weekSessions.map(s=>timelineItem(s,done)).join('')}</section></div>${plan.adaptations.filter(a=>a.week===roadmapVisibleWeek).length?adaptationCard(plan.adaptations.filter(a=>a.week===roadmapVisibleWeek).at(-1)):''}</div>`;
  $('#week-prev').onclick=()=>{roadmapVisibleWeek--;renderRoadmap()};$('#week-next').onclick=()=>{roadmapVisibleWeek++;renderRoadmap()};$('#week-select').onchange=e=>{roadmapVisibleWeek=Number(e.target.value);renderRoadmap()};
}
function timelineItem(session,done){const isDone=done.has(session.id),current=nextSession()?.id===session.id;return `<article class="timeline-item ${isDone?'done':''} ${current?'current':''}"><span class="timeline-number">${isDone?icon('check'):session.order}</span><div class="timeline-main"><h3>${html(session.title)}</h3><p>${session.minutes} phút · ${(session.reasonCodes||[]).map(c=>reasonLabels[c]).filter(Boolean).join(' · ')}</p></div><a class="timeline-action" href="#/activity/${session.id}">${isDone?'Học lại':current?'Học ngay':'Xem'}</a></article>`}
function adaptationCard(a){return `<section class="card lesson-card" style="margin-top:24px"><span class="skill-tag">Điều chỉnh tuần ${a.week}</span><h2 style="margin-top:12px">Kế hoạch đã học từ kết quả của bạn</h2><p class="muted">Ưu tiên: ${a.prioritySkills.map(s=>skillLabels[s]||s).join(', ')||'giữ nhịp cân bằng'}. ${a.missedSessionIds.length?`${a.missedSessionIds.length} phiên chưa hoàn thành được giữ lại.`:'Không có phiên bị bỏ lỡ.'}</p></section>`}

function coachContext(){const plan=store.activePlan,profile=plan?.professionalProfile;return `CEFR ${plan?.diagnostic?.inferredLevel||plan?.selfReportedLevel||'chưa xác định'}; mục tiêu ${plan?.track==='ielts'?'IELTS':'giao tiếp'}; ngành ${profile?.industryLabel||'chung'}${profile?.role?`; vai trò ${profile.role}`:''}.`}
function renderAiCoach(){
  const configured=!!(geminiService.key&&geminiService.model);
  $('#main-content').innerHTML=`<div class="page ai-coach-page">${pageHeader('AI Coach','Luyện tiếng Anh tự do bằng tin nhắn hoặc hội thoại giọng nói realtime.')}<section class="coach-shell card"><div class="coach-mode-tabs" role="tablist" aria-label="Chọn cách trò chuyện"><button type="button" role="tab" data-coach-mode="chat" aria-selected="${aiCoachMode==='chat'}">${icon('spark')} Nhắn tin</button><button type="button" role="tab" data-coach-mode="voice" aria-selected="${aiCoachMode==='voice'}">${icon('mic')} Nói chuyện</button></div>${configured?`<div id="coach-content"></div>`:`<div class="coach-setup"><span class="logo-mark">${icon('spark')}</span><h2>Cấu hình Gemini để bắt đầu</h2><p class="muted">AI Coach cần API key và một model generateContent. Key chỉ được giữ trên thiết bị này.</p><a class="btn btn-primary" href="#/settings">Mở cài đặt Gemini</a></div>`}</section></div>`;
  $$('[data-coach-mode]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.coachMode===aiCoachMode)return;liveService?.stop();liveService=null;aiCoachMode=button.dataset.coachMode;renderAiCoach()}));
  if(configured){if(aiCoachMode==='voice')renderCoachVoice();else renderCoachChat()}
}
function renderCoachChat(){
  const content=$('#coach-content');
  content.innerHTML=`<div class="coach-chat"><div id="coach-messages" class="coach-messages" role="log" aria-live="polite"></div><div id="coach-chat-error" class="inline-alert error" role="alert" hidden></div><form id="coach-chat-form" class="coach-composer"><label for="coach-input" class="sr-only">Tin nhắn cho AI Coach</label><textarea id="coach-input" rows="2" maxlength="1200" placeholder="Viết bằng tiếng Anh hoặc hỏi bằng tiếng Việt…" required></textarea><button class="btn btn-primary" type="submit" aria-label="Gửi tin nhắn">${icon('send')}<span>Gửi</span></button></form><button id="coach-clear" class="coach-clear" type="button">Xóa cuộc trò chuyện</button></div>`;
  renderCoachMessages();
  $('#coach-clear').addEventListener('click',()=>{aiCoachMessages=[];renderCoachMessages();$('#coach-input').focus()});
  $('#coach-chat-form').addEventListener('submit',sendCoachMessage);
  $('#coach-input').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();event.currentTarget.form.requestSubmit()}});
}
function renderCoachMessages(){
  const panel=$('#coach-messages');if(!panel)return;
  const welcome={role:'model',text:`Hi! I’m your English coach. We can practise everyday English${store.activePlan?.professionalProfile?` or ${store.activePlan.professionalProfile.industryLabel}`:''}. What would you like to talk about?`};
  panel.innerHTML=(aiCoachMessages.length?aiCoachMessages:[welcome]).map(message=>`<div class="coach-message ${message.role==='user'?'user':'ai'}"><span>${message.role==='user'?'Bạn':'AI Coach'}</span><p>${html(message.text)}</p></div>`).join('');panel.scrollTop=panel.scrollHeight;
}
async function sendCoachMessage(event){
  event.preventDefault();const input=$('#coach-input'),value=input.value.trim(),button=event.currentTarget.querySelector('button[type="submit"]'),error=$('#coach-chat-error');if(!value||button.disabled)return;
  aiCoachMessages.push({role:'user',text:value});input.value='';renderCoachMessages();button.disabled=true;button.innerHTML=`${icon('spark')}<span>Đang trả lời…</span>`;error.hidden=true;
  try{const reply=await geminiService.chat({messages:aiCoachMessages,learnerContext:coachContext()});aiCoachMessages.push({role:'model',text:reply});renderCoachMessages()}
  catch(err){error.textContent=`${err.message} Bạn có thể thử gửi lại.`;error.hidden=false}
  finally{button.disabled=false;button.innerHTML=`${icon('send')}<span>Gửi</span>`;input.focus()}
}
function renderCoachVoice(){
  const content=$('#coach-content');
  content.innerHTML=`<div class="coach-voice"><div class="voice-intro"><div><span class="skill-tag">Gemini Live · Beta</span><h2>Luyện phản xạ bằng giọng nói</h2><p class="muted">AI sẽ trả lời bằng tiếng Anh, giữ lượt nói ngắn và sửa lỗi quan trọng. Tối đa 10 phút; không lưu audio.</p></div><label class="field voice-topic"><span>Chủ đề</span><select id="coach-voice-topic"><option value="free">Trò chuyện tự do</option><option value="work">Giao tiếp công việc</option><option value="interview">Phỏng vấn xin việc</option><option value="travel">Du lịch</option><option value="daily">Đời sống hằng ngày</option></select></label></div><div class="speaking-stage">${liveVolumeHtml()}<button id="connect-live" class="btn btn-primary">Kết nối hội thoại</button><button id="mic-live" class="mic-button" type="button" hidden aria-label="Bật micro">${icon('mic')}</button><p id="speaking-status" class="speaking-status" role="status">Cần kết nối Internet và quyền micro.</p><p id="live-model-name" class="live-model-name" aria-live="polite" hidden></p><div id="live-transcript" class="transcript-panel" aria-live="polite"></div><div id="coach-feedback"></div><div class="activity-actions"><button id="finish-live" class="btn btn-secondary" type="button" hidden>Kết thúc & nhận feedback</button></div></div></div>`;
  bindLiveVolumeControl();
  $('#connect-live').addEventListener('click',connectCoachVoice);$('#mic-live').addEventListener('click',toggleCoachMicro);$('#finish-live').addEventListener('click',finishCoachVoice);
}
function coachVoiceScenario(){const topics={free:'Have a natural conversation and let the learner choose the direction.',work:'Practise a realistic workplace conversation, such as a meeting, status update, or clarification.',interview:'Act as an interviewer and ask one concise job interview question at a time.',travel:'Practise a useful travel situation such as a hotel, airport, restaurant, or directions.',daily:'Practise a friendly everyday conversation.'};return `You are a patient English speaking coach for a Vietnamese learner. ${topics[$('#coach-voice-topic')?.value]||topics.free} Learner context: ${coachContext()} Keep each turn under 35 words, ask one question at a time, and gently correct important mistakes.`}
async function connectCoachVoice(){const button=$('#connect-live');button.disabled=true;button.textContent='Đang kết nối…';try{const models=await geminiService.listLiveModels();if(!models.length)throw new Error('API key này chưa có model hỗ trợ Gemini Live.');const model=models[0];liveService=new LiveSpeakingService({outputVolume:readLiveVolume()});bindLiveEvents(liveService);await liveService.connect({apiKey:geminiService.key,model:model.name,scenario:coachVoiceScenario()});showLiveModel(model);activityStartedAt=Date.now();button.hidden=true;$('#coach-voice-topic').disabled=true;$('#mic-live').hidden=false;$('#finish-live').hidden=false}catch(error){$('#speaking-status').textContent=error.message;button.disabled=false;button.textContent='Thử kết nối lại'}}
let coachListening=false;
async function toggleCoachMicro(){try{if(!liveService)throw new Error('Hãy kết nối hội thoại trước.');if(coachListening){liveService.stopMicrophone();coachListening=false;$('#mic-live').classList.remove('active');$('#mic-live').setAttribute('aria-label','Bật micro')}else{await liveService.startMicrophone();coachListening=true;$('#mic-live').classList.add('active');$('#mic-live').setAttribute('aria-label','Tắt micro')}}catch(error){$('#speaking-status').textContent=`Không thể dùng micro: ${error.message}`}}
async function finishCoachVoice(){const button=$('#finish-live'),service=liveService;if(!service){toast('Phiên nói đã kết thúc.');return}button.disabled=true;button.textContent='Đang phân tích phát âm…';let pronunciationEvidence='';try{pronunciationEvidence=await service.requestPronunciationAssessment()}catch(error){toast(`Chưa phân tích được phát âm: ${error.message}`)}const transcript=service.stop()||[];liveService=null;coachListening=false;const text=transcript.map(item=>`${item.role}: ${item.text}`).join('\n');if(!text){toast('Chưa có hội thoại để đánh giá.');button.disabled=false;button.textContent='Bắt đầu phiên mới';return}button.textContent='Đang tổng hợp feedback…';let feedback=null;try{feedback=await geminiService.evaluate({type:'speaking',prompt:coachVoiceScenario(),answer:'',transcript:text,pronunciationEvidence});$('#coach-feedback').innerHTML=coachFeedbackHtml(feedback)}catch(error){$('#coach-feedback').innerHTML=`<div class="inline-alert error">${html(error.message)}</div>`}const record={id:`speaking-${Date.now()}`,scenario:`AI Coach · ${$('#coach-voice-topic').selectedOptions[0].textContent}`,transcript,feedback,durationSeconds:Math.max(1,Math.round((Date.now()-activityStartedAt)/1000)),createdAt:new Date().toISOString()};store.update(state=>state.speakingSessions.push(record));firebaseService.saveSpeaking(currentUser.uid,record).catch(error=>toast(`Chưa lưu được phiên nói: ${error.message}`));const fresh=button.cloneNode(true);fresh.disabled=false;fresh.textContent='Bắt đầu phiên mới';button.replaceWith(fresh);fresh.addEventListener('click',renderCoachVoice)}
const feedbackScoreLabels={fluency:'Độ trôi chảy',grammar:'Ngữ pháp',vocabulary:'Từ vựng',interaction:'Tương tác',pronunciation:'Phát âm',task:'Hoàn thành đề',coherence:'Mạch lạc'};
function feedbackScoresHtml(scores){return Object.entries(scores).map(([key,value])=>`<div class="score-box"><strong>${value===null?'—':value}</strong><small>${html(feedbackScoreLabels[key]||key)}</small></div>`).join('')}
function pronunciationFeedbackHtml(feedback){const detail=feedback.pronunciation;if(!detail)return '';const confidenceLabels={high:'Bằng chứng rõ',medium:'Bằng chứng vừa',low:'Bằng chứng hạn chế',insufficient:'Chưa đủ dữ liệu'};return `<section class="pronunciation-feedback"><div class="feedback-section-heading"><strong>Phát âm</strong><span class="skill-tag">${html(confidenceLabels[detail.confidence]||'Đang đánh giá')}</span></div><p>${html(detail.summary||'')}</p>${detail.observations?.length?`<ul>${detail.observations.map(item=>`<li><strong>${html(item.issue)}</strong>${item.evidence?` — ${html(item.evidence)}`:''}${item.tip?`<br><span>${html(item.tip)}</span>`:''}${item.example?`<br><span class="muted">Luyện: ${html(item.example)}</span>`:''}</li>`).join('')}</ul>`:''}</section>`}
function coachFeedbackHtml(feedback){return `<div class="ai-feedback"><h3>Phản hồi phiên nói</h3><div class="score-grid">${feedbackScoresHtml(feedback.scores)}</div>${pronunciationFeedbackHtml(feedback)}<strong>Cần cải thiện</strong><ul>${feedback.improvements.map(item=>`<li>${html(item)}</li>`).join('')}</ul>${feedback.betterPhrases?.length?`<strong>Cách nói tự nhiên hơn</strong><ul>${feedback.betterPhrases.map(item=>`<li>${html(item)}</li>`).join('')}</ul>`:''}</div>`}

function renderReview() {
  const items=Object.values(store.state.reviewItems).sort((a,b)=>a.nextReviewAt.localeCompare(b.nextReviewAt));
  $('#main-content').innerHTML=`<div class="page">${pageHeader('Ôn tập','Những điểm chưa vững sẽ quay lại theo nhịp 1–3–7 ngày.')}<div class="review-list">${items.length?items.map(item=>`<article class="card review-item"><div><span class="skill-tag">${skillLabels[item.skill]||item.skill}</span><h3>${html(item.prompt)}</h3><p>Lần ôn ${item.intervalIndex+1} · ${item.nextReviewAt<=today()?'Đến hạn hôm nay':`Tiếp theo ${item.nextReviewAt}`}</p><div class="mastery-bar"><span style="width:${Math.round(item.mastery*100)}%"></span></div></div><button class="btn btn-secondary review-now" data-id="${item.id}" ${item.nextReviewAt>today()?'disabled':''}>${item.nextReviewAt<=today()?'Đã ôn':'Chưa đến hạn'}</button></article>`).join(''):`<div class="empty-state"><h2>Chưa có mục cần ôn</h2><p>Lỗi sai từ bài học sẽ tự động xuất hiện tại đây.</p><a class="btn btn-primary" href="#/today">Học phiên tiếp theo</a></div>`}</div></div>`;
  $$('.review-now').forEach(button=>button.addEventListener('click',async()=>{if(!requireCloudConnection())return;const item={...store.state.reviewItems[button.dataset.id]};item.intervalIndex=Math.min(2,item.intervalIndex+1);const days=[1,3,7][item.intervalIndex];const date=new Date();date.setDate(date.getDate()+days);item.nextReviewAt=date.toISOString().slice(0,10);item.mastery=Math.min(1,item.mastery+.18);try{await firebaseService.saveReview(currentUser.uid,item);store.update(state=>{state.reviewItems[item.id]=item});toast('Đã ghi nhận lượt ôn.');renderReview()}catch(error){toast(`Chưa lưu được lượt ôn: ${error.message}`)}}));
}

function renderProgress() {
  const mastery=masteryBySkill(store.state.attempts),sessions=planSessions(),completed=sessions.filter(s=>store.completedIds.has(s.id)).length,totalMinutes=Object.values(store.state.studyDays).reduce((sum,d)=>sum+(d.totalMinutes||0),0),days=lastSevenDays(),grammar=grammarPathProgress(store.activePlan,grammarMap,store.state.attempts),grammarSessions=new Map(sessions.filter(s=>s.grammarTopicId).map(s=>[s.grammarTopicId,s]));
  $('#main-content').innerHTML=`<div class="page">${pageHeader('Tiến độ','Theo dõi độ vững từng kỹ năng, không chỉ số bài đã mở.')}<div class="stats-grid"><div class="stat-card"><span>Phiên hoàn thành</span><strong>${completed}/${sessions.length}</strong></div><div class="stat-card"><span>Thời gian học</span><strong>${totalMinutes} phút</strong></div><div class="stat-card"><span>Độ chính xác</span><strong>${averageScore()}%</strong></div><div class="stat-card"><span>Diagnostic</span><strong>${store.activePlan.diagnostic.percentage}%</strong></div></div><section class="card grammar-path-card"><div class="section-heading"><div><span class="skill-tag">Grammar Spine A1–B2</span><h2>Trình tự ngữ pháp của bạn</h2></div><p class="muted">Mastered từ 80% · 60–79% cần ôn · dưới 60% học lại</p></div><div class="grammar-path-list">${grammar.map((topic,index)=>{const session=grammarSessions.get(topic.id),statusLabels={not_started:'Chưa học',mastered:'Đã vững',review:'Cần ôn',relearn:'Học lại'};return `<a class="grammar-node ${topic.mastery.status}" href="${session?`#/activity/${session.id}`:'#/roadmap'}"><span>${index+1}</span><div><small>${html(topic.level)} · ${html(statusLabels[topic.mastery.status])}</small><strong>${html(topic.title)}</strong></div><b>${topic.mastery.attempts?`${topic.mastery.score}%`:'—'}</b></a>`}).join('')}</div></section><div class="progress-layout"><section class="card chart-card"><h2>Mastery theo kỹ năng</h2><div class="skill-bars">${Object.keys(skillLabels).filter(k=>k!=='mixed').map(skill=>skillBar(skill,mastery[skill]||0)).join('')}</div></section><section class="card chart-card"><h2>7 ngày gần đây</h2><div class="week-bars">${days.map(day=>`<div class="day-bar"><i style="--h:${Math.min(100,(store.state.studyDays[day.iso]?.totalMinutes||0)*2.5)}%"></i><span>${day.label}</span></div>`).join('')}</div></section></div></div>`;
}
function skillBar(skill,value){return `<div class="skill-row"><span>${skillLabels[skill]}</span><div class="bar"><span style="width:${value}%"></span></div><strong>${value}%</strong></div>`}
function averageScore(){const attempts=store.state.attempts.filter(a=>!a.sessionComplete&&Number.isFinite(Number(a.score)));return attempts.length?Math.round(100*attempts.reduce((s,a)=>s+Number(a.score),0)/attempts.length):0}
function lastSevenDays(){const fmt=new Intl.DateTimeFormat('vi',{weekday:'short'});return Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return{iso:d.toISOString().slice(0,10),label:fmt.format(d)}})}

function renderSettings() {
  const settings=store.state.settings,keyPresent=!!geminiService.key;
  $('#main-content').innerHTML=`<div class="page">${pageHeader('Cài đặt','Quản lý giao diện, AI và tài khoản trên thiết bị này.')}<div class="settings-grid"><section class="card settings-section"><h2>Giao diện và học tập</h2><div class="setting-row"><div class="setting-copy"><strong>Chế độ tối</strong><small>Đồng bộ cài đặt giao diện lên tài khoản.</small></div><label class="switch"><input id="theme-switch" type="checkbox" ${settings.theme==='dark'?'checked':''}><span></span></label></div><div class="setting-row"><div class="setting-copy"><strong>Lịch hiện tại</strong><small>${store.activePlan.schedule.daysPerWeek} ngày/tuần · ${store.activePlan.schedule.minutesPerDay} phút/ngày</small></div><button id="new-goal" class="btn btn-secondary">Đổi mục tiêu</button></div></section><section class="card settings-section"><h2>Cài ứng dụng</h2><div class="setting-row"><div class="setting-copy"><strong>English Assistant trên màn hình chính</strong><small>Mở trong cửa sổ riêng; cần Internet để tải và lưu tiến độ.</small></div><button class="btn btn-secondary" type="button" data-pwa-install>Cài đặt</button></div></section><section class="card settings-section"><h2>Gemini AI trên thiết bị</h2><p class="muted">Key không được gửi lên Firestore. Nếu bật ghi nhớ, key nằm trong localStorage của trình duyệt này.</p><div class="api-form"><input id="api-key" type="password" autocomplete="off" placeholder="Dán Gemini API key" value="${keyPresent?'••••••••••••':''}" aria-label="Gemini API key"><button id="load-models" class="btn btn-secondary">Tải model</button></div><label class="setting-row"><div class="setting-copy"><strong>Ghi nhớ trên thiết bị này</strong><small>Chỉ bật trên thiết bị cá nhân.</small></div><span class="switch"><input id="remember-key" type="checkbox" ${!!localStorage.getItem('ela_gemini_key')?'checked':''}><span></span></span></label><div class="model-row"><select id="model-select" aria-label="Gemini model"><option value="${html(geminiService.model)}">${geminiService.model?html(geminiService.model):'Tải danh sách model để chọn'}</option></select><button id="save-ai" class="btn btn-primary">Lưu AI</button></div><p id="ai-status" class="form-hint">${keyPresent?'API key đã được cấu hình trên thiết bị.':'Grammar cá nhân hóa, Writing và Speaking feedback cần API key.'}</p></section><section class="card settings-section"><h2>Tài khoản</h2><div class="setting-row"><div class="setting-copy"><strong>${html(store.state.profile.displayName)}</strong><small>${html(store.state.profile.email)}</small></div><button id="logout" class="btn btn-danger">${icon('logout')} Đăng xuất</button></div></section></div></div>`;
  refreshPwaInstall();
  $('#theme-switch').addEventListener('change',toggleTheme);$('#logout').addEventListener('click',event=>requestLogout(event.currentTarget));$('#new-goal').addEventListener('click',newGoal);$('#load-models').addEventListener('click',loadModels);$('#save-ai').addEventListener('click',saveAiSettings);
}
function toggleTheme(){const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;store.update(s=>s.settings.theme=theme);firebaseService.saveSettings(currentUser.uid,store.state.settings).catch(()=>{});renderAccountTheme();}
async function loadModels(){const keyInput=$('#api-key').value.trim(),key=keyInput&&!keyInput.startsWith('••')?keyInput:geminiService.key,status=$('#ai-status'),button=$('#load-models');button.disabled=true;status.textContent='Đang tải model...';try{const models=await geminiService.listModels(key);$('#model-select').innerHTML=models.map(m=>`<option value="${html(m.id)}" ${m.id===geminiService.model?'selected':''}>${html(m.name)}</option>`).join('');status.textContent=`Đã tìm thấy ${models.length} model hỗ trợ generateContent.`;if(keyInput&&!keyInput.startsWith('••'))$('#api-key').dataset.pendingKey=keyInput}catch(error){status.textContent=error.message}finally{button.disabled=false}}
function saveAiSettings(){const input=$('#api-key'),pending=input.dataset.pendingKey||(!input.value.startsWith('••')?input.value:'')||geminiService.key,model=$('#model-select').value;if(!pending||!model){$('#ai-status').textContent='Hãy nhập key, tải và chọn model.';return}geminiService.configure(pending,$('#remember-key').checked,model);$('#ai-status').textContent='Đã lưu cấu hình AI trên thiết bị này.';toast('Đã cập nhật Gemini.');}
async function newGoal(){if(!requireCloudConnection()||!confirm('Lộ trình hiện tại sẽ được lưu vào lịch sử và bạn sẽ tạo lộ trình mới. Tiếp tục?'))return;try{await firebaseService.upsertProfile(currentUser,false,null);store.update(s=>{s.onboardingComplete=false;s.currentPlanId=null});$('#app-shell').hidden=true;showOnboarding()}catch(error){toast(`Chưa thể đổi mục tiêu: ${error.message}`)}}

async function renderActivity(sessionId) {
  let session=planSessions().find(s=>s.id===sessionId);if(!session){location.hash='#/today';return}
  if(session.grammarTopicId&&!store.state.grammarLessons?.[grammarLessonKey(store.activePlan.id,session.grammarTopicId)]&&geminiService.key&&geminiService.model&&navigator.onLine){
    $('#main-content').innerHTML=`<div class="activity-page"><div class="activity-top"><a class="icon-btn" href="#/roadmap" aria-label="Quay lại">${icon('back')}</a></div><article class="card activity-card grammar-loading" role="status"><span class="logo-mark">${icon('spark')}</span><div><div class="eyebrow">GRAMMAR SPINE</div><h1>Đang cá nhân hóa bài học…</h1><p class="muted">Gemini đang tạo ví dụ theo mục tiêu và ngành nghề của bạn. Nếu AI lỗi, app sẽ dùng bài học offline có sẵn.</p></div></article></div>`;
    try{const topic=grammarTopicById(grammarMap,session.grammarTopicId),profile=store.activePlan.professionalProfile||{},lesson=await geminiService.generateGrammarLesson({topic,learnerContext:`CEFR ${topic.level}; mục tiêu ${store.activePlan.track==='ielts'?'IELTS':'giao tiếp'}; ngành ${profile.industryLabel||'chung'}${profile.role?`; vai trò ${profile.role}`:''}.`}),key=grammarLessonKey(store.activePlan.id,topic.id),record={...lesson,id:key,planId:store.activePlan.id,grammarVersion:grammarMap.version,createdAt:new Date().toISOString()};store.update(state=>{state.grammarLessons[key]=record});await firebaseService.saveGrammarLesson(currentUser.uid,record);session=planSessions().find(s=>s.id===sessionId);toast('Đã tạo bài grammar cá nhân hóa bằng Gemini.')}catch(error){toast(`Đang dùng bài grammar có sẵn: ${error.message}`)}
    if(location.hash!==`#/activity/${sessionId}`)return;
  }
  activityStartedAt=Date.now();renderActivityStep(session,0,[]);
}
function renderActivityStep(session,index,results) {
  const activity=session.activities[index],pct=Math.round(index/session.activities.length*100);
  $('#main-content').innerHTML=`<div class="activity-page"><div class="activity-top"><a class="icon-btn" href="#/roadmap" aria-label="Quay lại">${icon('back')}</a><div class="activity-progress" aria-label="Tiến trình phiên học"><span style="width:${pct}%"></span></div><strong>${index+1}/${session.activities.length}</strong></div><article class="card activity-card"><span class="skill-tag">${skillLabels[activity.skill||session.skill]||session.skill}</span><h1>${html(activity.title||session.title)}</h1><div id="activity-body"></div></article></div>`;
  const body=$('#activity-body');
  if(activity.type==='flashcards')renderFlashcards(body,activity,()=>finishActivity(session,index,results,{score:1,answer:'reviewed'}));
  else if(activity.type==='lesson-intro')renderLessonIntro(body,activity,()=>finishActivity(session,index,results,{score:1,scored:false,answer:'viewed'}));
  else if(activity.type==='lesson-recap')renderLessonRecap(body,activity,rating=>finishActivity(session,index,results,{score:1,scored:false,answer:rating}));
  else if(activity.type==='grammar-concept')renderGrammarConcept(body,activity,()=>finishActivity(session,index,results,{score:1,answer:'studied'}));
  else if(['mcq','reading','listening'].includes(activity.type))renderChoice(body,activity,session,index,results);
  else if(activity.type==='fill')renderFill(body,activity,session,index,results);
  else if(activity.type==='reorder')renderReorder(body,activity,session,index,results);
  else if(['writing','short'].includes(activity.type))renderSubjective(body,activity,session,index,results);
  else if(activity.type==='speaking-live')renderSpeaking(body,activity,session,index,results);
}
function renderLessonIntro(body,a,onDone){body.innerHTML=`<div class="grammar-source"><span class="skill-tag">LEARNING LOOP</span></div><section class="grammar-theory"><h2>Vì sao học nội dung này?</h2><p>${html(a.objective)}</p></section><section class="grammar-examples"><h2>Sau phiên này, bạn sẽ</h2>${a.outcomes.map((item,index)=>`<article><strong>${index+1}</strong><p>${html(item)}</p></article>`).join('')}</section><div class="activity-actions"><button id="start-learning-loop" class="btn btn-primary">Bắt đầu luyện ${icon('arrow')}</button></div>`;$('#start-learning-loop').addEventListener('click',onDone)}
function renderLessonRecap(body,a,onDone){body.innerHTML=`<p class="lead">Nhìn lại mục tiêu và chọn mức độ bạn có thể tự làm lại mà không xem đáp án.</p><div class="feedback-box"><strong>Checklist cuối phiên</strong><ul>${a.checks.map(item=>`<li>${html(item)}</li>`).join('')}</ul></div><div class="activity-options"><button class="option-btn" data-rating="review">Cần ôn lại</button><button class="option-btn" data-rating="okay">Tạm ổn</button><button class="option-btn" data-rating="confident">Tự tin vận dụng</button></div>`;$$('[data-rating]',body).forEach(button=>button.addEventListener('click',()=>onDone(button.dataset.rating)))}
function renderGrammarConcept(body,a,onDone){const lesson=a.lesson,topic=a.topic,source=lesson.source==='gemini'?'Gemini cá nhân hóa':'Nội dung offline';body.innerHTML=`<div class="grammar-stepper" aria-label="Các bước bài grammar"><span class="active">1. Hiểu</span><span>2. Nhận biết</span><span>3. Luyện</span><span>4. Vận dụng</span></div><div class="grammar-source"><span class="skill-tag">${html(topic.level)} · ${html(source)}</span></div><section class="grammar-theory"><h2>Ý nghĩa và cách dùng</h2><p>${html(lesson.summary)}</p><div class="grammar-form"><span>Công thức</span><strong>${html(lesson.form)}</strong></div><ul>${lesson.uses.map(use=>`<li>${html(use)}</li>`).join('')}</ul></section><section class="grammar-examples"><h2>Ví dụ trong ngữ cảnh</h2>${lesson.examples.map(item=>`<article><p lang="en">${html(item.sentence)}</p><small>${html(item.meaning)}</small></article>`).join('')}</section><section class="grammar-errors"><h2>Lỗi cần tránh</h2><ul>${lesson.commonErrors.map(item=>`<li>${html(item)}</li>`).join('')}</ul></section><div class="activity-actions"><button id="grammar-understood" class="btn btn-primary">Bắt đầu luyện ${icon('arrow')}</button></div>`;$('#grammar-understood').addEventListener('click',onDone)}
function renderFlashcards(body,a,onDone){body.innerHTML=`<p class="lead">Chạm vào từng thẻ để xem nghĩa.</p><div class="activity-options">${a.cards.map(([front,back])=>`<button class="option-btn flashcard" data-front="${html(front)}" data-back="${html(back)}"><strong>${html(front)}</strong></button>`).join('')}</div><div class="activity-actions"><button id="flash-done" class="btn btn-primary">Đã xem tất cả ${icon('arrow')}</button></div>`;$$('.flashcard',body).forEach(btn=>btn.addEventListener('click',()=>{btn.innerHTML=btn.dataset.flipped?`<strong>${btn.dataset.front}</strong>`:`<strong>${btn.dataset.front}</strong><br><span class="muted">${btn.dataset.back}</span>`;btn.dataset.flipped=btn.dataset.flipped?'':'1'}));$('#flash-done').addEventListener('click',onDone)}
function renderChoice(body,a,session,index,results){body.innerHTML=`${a.passage?`<div class="prompt-box">${html(a.passage)}</div>`:''}${a.type==='listening'?`<button id="listen-btn" class="btn btn-secondary">${icon('volume')} Nghe đoạn hội thoại</button>`:''}<div class="prompt-box">${html(a.prompt)}</div><div class="activity-options">${a.options.map((o,i)=>`<button class="option-btn" data-value="${i}">${html(o)}</button>`).join('')}</div><div id="answer-feedback"></div><div class="activity-actions"><button id="check-answer" class="btn btn-primary" disabled>Kiểm tra</button></div>`;let selected=null,checked=null;$$('.option-btn',body).forEach(btn=>btn.addEventListener('click',()=>{if(checked)return;$$('.option-btn',body).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');selected=Number(btn.dataset.value);$('#check-answer').disabled=false}));$('#listen-btn')?.addEventListener('click',()=>speakText(a.text));$('#check-answer').addEventListener('click',()=>{if(checked){finishActivity(session,index,results,checked);return}const ok=selected===a.answer;checked={score:ok?1:0,answer:selected};$$('.option-btn',body).forEach(btn=>{btn.disabled=true;if(Number(btn.dataset.value)===a.answer)btn.classList.add('correct');else if(btn.classList.contains('selected'))btn.classList.add('wrong')});showAnswerFeedback(a,ok);$('#check-answer').textContent='Tiếp tục';})}
function renderFill(body,a,session,index,results){body.innerHTML=`<div class="prompt-box">${html(a.prompt)}</div><label class="field"><span>Câu trả lời</span><input id="fill-answer" autocomplete="off"></label><div id="answer-feedback"></div><div class="activity-actions"><button id="check-answer" class="btn btn-primary">Kiểm tra</button></div>`;let checked=null;$('#check-answer').addEventListener('click',()=>{if(checked){finishActivity(session,index,results,checked);return}const value=$('#fill-answer').value.trim(),ok=normalize(value)===normalize(a.answer);checked={score:ok?1:0,answer:value};showAnswerFeedback(a,ok,`Đáp án: ${a.answer}`);$('#fill-answer').disabled=true;$('#check-answer').textContent='Tiếp tục';})}
function renderReorder(body,a,session,index,results){let picked=[],checked=null;body.innerHTML=`<div class="prompt-box">${html(a.prompt)}</div><div id="constructed" class="constructed-answer"><span class="muted">Chọn các cụm từ theo thứ tự</span></div><div class="reorder-bank">${a.words.map((w,i)=>`<button class="word-chip" data-index="${i}">${html(w)}</button>`).join('')}</div><div id="answer-feedback"></div><div class="activity-actions"><button id="reset-order" class="btn btn-secondary">Làm lại</button><button id="check-answer" class="btn btn-primary" disabled>Kiểm tra</button></div>`;const update=()=>{$('#constructed').innerHTML=picked.length?picked.map(i=>`<button class="word-chip" data-picked="${i}">${html(a.words[i])}</button>`).join(''):'<span class="muted">Chọn các cụm từ theo thứ tự</span>';$$('[data-picked]').forEach(b=>b.addEventListener('click',()=>{if(checked)return;picked=picked.filter(i=>i!==Number(b.dataset.picked));$(`.word-chip[data-index="${b.dataset.picked}"]`).classList.remove('used');update()}));$('#check-answer').disabled=!picked.length};$$('.reorder-bank .word-chip').forEach(b=>b.addEventListener('click',()=>{if(!checked&&!picked.includes(Number(b.dataset.index))){picked.push(Number(b.dataset.index));b.classList.add('used');update()}}));$('#reset-order').addEventListener('click',()=>{if(checked)return;picked=[];$$('.reorder-bank .word-chip').forEach(b=>b.classList.remove('used'));update()});$('#check-answer').addEventListener('click',()=>{if(checked){finishActivity(session,index,results,checked);return}const value=picked.map(i=>a.words[i]).join(' ').replace(/\s+([,.?])/g,'$1'),ok=normalize(value)===normalize(a.answer);checked={score:ok?1:0,answer:value};showAnswerFeedback(a,ok,`Đáp án: ${a.answer}`);$('#check-answer').textContent='Tiếp tục';})}
function renderSubjective(body,a,session,index,results){body.innerHTML=`<div class="prompt-box">${html(a.prompt)}</div><label class="field"><span>Câu trả lời của bạn</span><textarea id="subjective-answer" class="writing-area"></textarea></label><div id="ai-result"></div><div class="activity-actions"><button id="submit-subjective" class="btn btn-primary">${geminiService.key&&geminiService.model?`${icon('spark')} Nhận phản hồi AI`:'Xem gợi ý & tự đánh giá'}</button></div>`;let ready=null;$('#submit-subjective').addEventListener('click',async()=>{if(ready){finishActivity(session,index,results,ready);return}const answer=$('#subjective-answer').value.trim();if(answer.length<8){toast('Hãy viết câu trả lời trước.');return}const btn=$('#submit-subjective');btn.disabled=true;let score=.7,feedback=null;try{if(geminiService.key&&geminiService.model){btn.textContent='Đang phân tích...';feedback=await geminiService.evaluate({type:'writing',prompt:a.prompt,answer});score=Object.values(feedback.scores).reduce((x,y)=>x+y,0)/(Object.keys(feedback.scores).length*9);renderAiFeedback(feedback)}else{$('#ai-result').innerHTML=`<div class="feedback-box"><strong>Gợi ý tham khảo</strong><p>${html(a.sample||'Kiểm tra cấu trúc, độ rõ ý và từ vựng của câu trả lời.')}</p></div>`}ready={score,answer,feedback};btn.disabled=false;btn.textContent='Tiếp tục'}catch(error){$('#ai-result').innerHTML=`<div class="inline-alert error">${html(error.message)} <button id="retry-ai" class="btn btn-secondary">Thử lại</button></div>`;$('#retry-ai').onclick=()=>btn.click();btn.disabled=false}})}
function showAnswerFeedback(a,ok,extra=''){const box=$('#answer-feedback');box.innerHTML=`<div class="feedback-box"><strong>${ok?'Chính xác':'Chưa đúng'}</strong><p>${html(extra||a.explanation||'')}</p>${a.explanation&&extra?`<p class="muted">${html(a.explanation)}</p>`:''}</div>`}
function renderAiFeedback(f){$('#ai-result').innerHTML=`<div class="ai-feedback"><h3>Phản hồi AI</h3><div class="score-grid">${feedbackScoresHtml(f.scores)}</div>${f.summary?`<p>${html(f.summary)}</p>`:''}${pronunciationFeedbackHtml(f)}<strong>Cần cải thiện</strong><ul>${f.improvements.map(x=>`<li>${html(x)}</li>`).join('')}</ul>${f.rewrite?`<strong>Gợi ý viết lại</strong><div class="prompt-box">${html(f.rewrite)}</div>`:''}</div>`}
function normalize(value){return String(value).trim().toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ').replace(/\s+([,.?])/g,'$1')}
function speakText(text){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=.9;speechSynthesis.speak(utterance)}

async function finishActivity(session,index,results,result) {
  if(!requireCloudConnection())return;
  const a=session.activities[index],attempt=buildAttempt(session,a,result);results.push(attempt);store.recordAttempt(attempt);await firebaseService.saveAttempt(currentUser.uid,attempt).catch(()=>{});if(attempt.reviewItem)firebaseService.saveReview(currentUser.uid,attempt.reviewItem).catch(()=>{});
  if(index<session.activities.length-1){renderActivityStep(session,index+1,results);return}
  const completion=store.completeSession(session.id,Math.max(1,Math.round((Date.now()-activityStartedAt)/60000)));await firebaseService.saveAttempt(currentUser.uid,completion).catch(()=>{});const day=store.state.studyDays[today()];firebaseService.saveStudyDay(currentUser.uid,day).catch(()=>{});
  const plan=store.activePlan,weekDone=plan.sessions.filter(s=>s.week===session.week).every(s=>store.completedIds.has(s.id)),nextWeek=session.week+1;if(weekDone&&nextWeek<=(plan.totalWeeks||2)&&!plan.adaptations.some(a=>a.week===nextWeek)){adaptNextWeek(plan,store.state.attempts,session.week);store.update(()=>{});await firebaseService.savePlan(currentUser.uid,plan).catch(error=>toast(`Chưa lưu được điều chỉnh tuần mới: ${error.message}`));}
  renderCompletion(session,results);
}
function buildAttempt(session,a,result){const now=new Date(),score=Number(result.score||0),scored=result.scored!==false,id=`${a.id}-${now.getTime()}`,grammarTopicId=session.grammarTopicId||null;let reviewItem=null;if(scored&&score<.8&&a.type!=='writing'&&a.type!=='short'&&a.type!=='speaking-live'&&a.type!=='grammar-concept'){const old=store.state.reviewItems[a.id],intervalIndex=old?.intervalIndex||0,date=new Date();date.setDate(date.getDate()+[1,3,7][intervalIndex]);reviewItem={id:a.id,skill:a.skill||session.skill,grammarTopicId,prompt:a.prompt||a.title,mastery:Math.max(0,score),intervalIndex,nextReviewAt:date.toISOString().slice(0,10),updatedAt:now.toISOString()}}return{id,sessionId:session.id,activityId:a.id,type:a.type,skill:a.skill||session.skill,grammarTopicId,answer:result.answer,score,scored,feedback:result.feedback||null,reviewItem,date:today(),durationSeconds:Math.round((Date.now()-activityStartedAt)/1000),updatedAt:now.toISOString()}}
function renderCompletion(session,results){const scored=results.filter(result=>result.scored!==false),score=scored.length?Math.round(100*scored.reduce((sum,result)=>sum+result.score,0)/scored.length):100;$('#main-content').innerHTML=`<div class="activity-page"><article class="card activity-card" style="text-align:center"><span class="logo-mark" style="margin:0 auto 20px">${icon('check')}</span><div class="eyebrow">PHIÊN HOÀN THÀNH</div><h1>${score}% chính xác</h1><p class="lead" style="margin-inline:auto">${score>=80?'Bạn đang nắm rất tốt nội dung hôm nay.':score>=60?'Nền tảng ổn. Những điểm sai đã được đưa vào Ôn tập.':'Đừng lo — app đã lưu những điểm cần củng cố.'}</p><div class="activity-actions" style="justify-content:center"><a href="#/today" class="btn btn-primary">Về Hôm nay</a><a href="#/review" class="btn btn-secondary">Xem ôn tập</a></div></article></div>`}

async function renderSpeaking(body,a,session,index,results) {
  body.innerHTML=`<div class="speaking-stage"><div class="inline-alert info">Beta · Tối đa 10 phút · Transcript được lưu, audio không được lưu.</div><p class="lead" style="margin-inline:auto">${html(a.scenario)}</p>${liveVolumeHtml()}<button id="connect-live" class="btn btn-primary">Kết nối hội thoại</button><button id="mic-live" class="mic-button" hidden aria-label="Bật micro">${icon('mic')}</button><p id="speaking-status" class="speaking-status">Cần kết nối Internet và quyền micro.</p><p id="live-model-name" class="live-model-name" aria-live="polite" hidden></p><div id="live-transcript" class="transcript-panel" aria-live="polite"></div><div class="activity-actions"><button id="finish-live" class="btn btn-secondary" hidden>Kết thúc & nhận feedback</button></div></div>`;
  bindLiveVolumeControl();
  $('#connect-live').addEventListener('click',async()=>{const btn=$('#connect-live');btn.disabled=true;btn.textContent='Đang kết nối...';try{const models=await geminiService.listLiveModels();if(!models.length)throw new Error('API key này không có model hỗ trợ Live API.');const model=models[0];liveService=new LiveSpeakingService({outputVolume:readLiveVolume()});bindLiveEvents(liveService);await liveService.connect({apiKey:geminiService.key,model:model.name,scenario:a.scenario});showLiveModel(model);btn.hidden=true;$('#mic-live').hidden=false;$('#finish-live').hidden=false}catch(error){$('#speaking-status').textContent=error.message;btn.disabled=false;btn.textContent='Thử kết nối lại'}});
  let listening=false;$('#mic-live').addEventListener('click',async()=>{try{if(listening){liveService.stopMicrophone();listening=false;$('#mic-live').classList.remove('active')}else{await liveService.startMicrophone();listening=true;$('#mic-live').classList.add('active')}}catch(error){$('#speaking-status').textContent=`Không thể dùng micro: ${error.message}`}});
  let ready=null;$('#finish-live').addEventListener('click',async()=>{if(ready){finishActivity(session,index,results,ready);return}const service=liveService;if(!service){toast('Phiên nói đã kết thúc.');return}const btn=$('#finish-live');btn.disabled=true;btn.textContent='Đang phân tích phát âm...';let pronunciationEvidence='';try{pronunciationEvidence=await service.requestPronunciationAssessment()}catch(error){toast(`Chưa phân tích được phát âm: ${error.message}`)}const transcript=service.stop()||[];liveService=null;const text=transcript.map(t=>`${t.role}: ${t.text}`).join('\n');if(!text){toast('Chưa có hội thoại để đánh giá.');btn.disabled=false;btn.textContent='Kết thúc & nhận feedback';return}btn.textContent='Đang tổng hợp feedback...';let feedback=null,score=.7;try{feedback=await geminiService.evaluate({type:'speaking',prompt:a.scenario,answer:'',transcript:text,pronunciationEvidence});const scored=Object.values(feedback.scores).filter(Number.isFinite);score=scored.reduce((x,y)=>x+y,0)/(Math.max(1,scored.length)*9);renderAiFeedback(feedback)}catch(error){toast(error.message)}const record={id:`speaking-${Date.now()}`,scenario:a.title,transcript,feedback,durationSeconds:Math.round((Date.now()-activityStartedAt)/1000),createdAt:new Date().toISOString()};store.update(s=>s.speakingSessions.push(record));firebaseService.saveSpeaking(currentUser.uid,record).catch(()=>{});ready={score,answer:text,feedback};btn.disabled=false;btn.textContent='Tiếp tục';});
}
function readLiveVolume(){const value=Number(localStorage.getItem(LIVE_VOLUME_KEY));return Number.isFinite(value)&&value>=0&&value<=1?value:.35}
function liveVolumeHtml(){const percent=Math.round(readLiveVolume()*100);return `<div class="live-volume"><label for="live-volume-range">${icon('volume')}<span>Âm lượng AI</span><output id="live-volume-value" for="live-volume-range">${percent}%</output></label><input id="live-volume-range" type="range" min="0" max="100" step="1" value="${percent}" aria-label="Âm lượng giọng nói AI"></div>`}
function bindLiveVolumeControl(){const range=$('#live-volume-range'),output=$('#live-volume-value');if(!range||!output)return;range.addEventListener('input',()=>{const percent=Number(range.value);output.value=`${percent}%`;localStorage.setItem(LIVE_VOLUME_KEY,String(percent/100));liveService?.setOutputVolume(percent/100)})}
function bindLiveEvents(service){service.addEventListener('status',e=>{$('#speaking-status').textContent=e.detail.message});service.addEventListener('error',e=>{$('#speaking-status').textContent=e.detail.message});service.addEventListener('transcript',e=>{$('#live-transcript').innerHTML=e.detail.transcript.map(t=>`<div class="bubble ${t.role}">${html(t.text)}</div>`).join('');$('#live-transcript').scrollTop=$('#live-transcript').scrollHeight})}
function showLiveModel(model){const node=$('#live-model-name');if(!node)return;const id=String(model.name||'').replace(/^models\//,''),display=String(model.displayName||'').trim();node.textContent=`Model voice: ${display&&display!==id?`${display} · `:''}${id}`;node.title=id;node.hidden=false}

function registerServiceWorker(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('./sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)toast('Có phiên bản mới. Tải lại trang để cập nhật.')})})}).catch(()=>{})}

init().catch(error=>showAuthError(`Không thể khởi động ứng dụng: ${error.message}`));
